const MENTORS_IMAGE_BASE = '/wp-content/uploads/2026/07/mentors';

const MENTORS = [
  {
    name: 'Sahla CA',
    role: 'Data Scientist & AI Specialist',
    image: `${MENTORS_IMAGE_BASE}/sahla-ca.png`,
    bio: 'Data Scientist with a strong foundation in analytics, machine learning, AI, and GenAI. Brings a unique perspective from a decade-long biotech career, combining scientific research with data-driven problem solving.',
    linkedin: 'https://www.linkedin.com/in/sahla-ca-952043236/',
  },
  {
    name: 'Rajesh Kumar',
    role: 'IT Leader & Career Mentor',
    image: `${MENTORS_IMAGE_BASE}/rajesh-kumar.png`,
    photoPosition: 'center 22%',
    bio: 'With 30 years of IT expertise, Rajesh mentors for advancement, collaborating with colleges and corporates to address employment challenges and empower learners through edu-tech.',
    linkedin: 'https://www.linkedin.com/in/rajesh-shanmugam-12930b1/',
  },
  {
    name: 'Vishwanath',
    role: 'Senior Java & Full Stack Mentor',
    image: `${MENTORS_IMAGE_BASE}/vishwanath.png`,
    photoPosition: 'center 20%',
    bio: 'Two decades of hands-on experience in Python and Java. Delivers innovative solutions across diverse domains and builds strong programming fundamentals for aspiring developers.',
    linkedin: 'https://www.linkedin.com/in/vishwanath-ramadass-48842392/',
  },
  {
    name: 'Sobha',
    role: 'Data Analytics Mentor',
    image: `${MENTORS_IMAGE_BASE}/sobha.png`,
    photoPosition: 'center 5%',
    photoScale: 1.58,
    photoOrigin: 'center top',
    bio: 'Combines polytechnic teaching experience with hands-on expertise in Python, SQL, Power BI, Excel, and Git — guiding learners to bridge theory with real-world application.',
    linkedin: 'https://www.linkedin.com/in/shobha-p-a80932189/',
  },
  {
    name: 'Raghavan',
    role: 'Data Engineering Mentor',
    image: `${MENTORS_IMAGE_BASE}/raghavan.png`,
    bio: 'Expert in Python, Pandas, SQL, Data Warehousing, Snowflake, PySpark, and AWS. Known for hands-on mentorship that prepares learners for high-impact data engineering roles.',
    linkedin: 'https://www.linkedin.com/in/raghavan-s-n-111126202/',
  },
  {
    name: 'Mangala Narayan',
    role: 'Life Coach & Wellness Practitioner',
    image: `${MENTORS_IMAGE_BASE}/mangala-narayan.png`,
    photoPosition: 'center 28%',
    photoScale: 0.88,
    photoOrigin: 'center center',
    bio: 'Certified Life Coach and Meditation Practitioner who empowers individuals through tailored coaching, guided meditations, and holistic well-being practices.',
    linkedin: 'https://www.linkedin.com/in/mangala-narayan-a6936b25/',
  },
  {
    name: 'Deepa Bushan',
    role: 'Soft Skills & Career Coach',
    image: `${MENTORS_IMAGE_BASE}/deepa-bushan.jpeg`,
    bio: 'Over 7 years of corporate experience focused on nurturing newcomers with essential soft skills — communication, corporate etiquette, and confidence building.',
    linkedin: 'https://www.linkedin.com/in/deepa-bhushan-b8163319/',
  },
  {
    name: 'Nandini S N',
    role: 'DevOps Mentor',
    image: `${MENTORS_IMAGE_BASE}/nandini-s-n.png`,
    bio: 'DevOps mentor blending innovative strategies with cutting-edge technologies to sculpt resilient, agile workflows and elevate teams to peak performance.',
    linkedin: 'https://www.linkedin.com/in/nandini-s-n-22b3678b/',
  },
  {
    name: 'Lakshmi Kuppanna',
    role: 'HR & Finance Leader',
    image: `${MENTORS_IMAGE_BASE}/lakshmi-kuppanna.jpeg`,
    bio: '18+ years of HR Finance & Admin experience, driving employee-focused finance operations and motivating freshers to upskill and transform their career journeys.',
    linkedin: 'https://www.linkedin.com/in/lakshmi-kuppanna-36326875/',
  },
  {
    name: 'Nethravathi T',
    role: 'Full Stack MERN Developer',
    image: `${MENTORS_IMAGE_BASE}/nethravathi-t.png`,
    bio: 'Software Developer with 4+ years building scalable MERN applications. Mentors aspiring developers in Data Structures and Algorithms to strengthen problem-solving skills.',
    linkedin: 'https://www.linkedin.com/in/nethravathit/',
  },
  {
    name: 'Divya Shree G V',
    role: 'Oracle SQL',
    image: `${MENTORS_IMAGE_BASE}/divya-shree-gv.jpeg`,
    photoPosition: 'center 18%',
    bio: 'Oracle SQL mentor helping learners build strong database fundamentals and write efficient, production-ready SQL.',
    linkedin: 'https://www.linkedin.com/in/divya-shree-g-v-22a105214/',
  },
  {
    name: 'Anand Kumar T M',
    role: 'Data Scientist',
    image: `${MENTORS_IMAGE_BASE}/anandkumar-tm.jpeg`,
    photoPosition: 'center 12%',
    bio: 'Data Scientist mentoring learners in Python, SQL, PySpark, Databricks, Snowflake, AI, and ML to build real-world data solutions.',
    linkedin: 'https://www.linkedin.com/in/t-m-anand-kumar-393493425/',
  },
  {
    name: 'Yeddula Jagadeesh',
    role: 'Java & MERN Full Stack',
    image: `${MENTORS_IMAGE_BASE}/yeddula-jagadeesh.jpeg`,
    photoPosition: 'center 20%',
    bio: 'Java and MERN Full Stack mentor helping learners build end-to-end web applications with strong fundamentals and practical project experience.',
    linkedin: 'https://www.linkedin.com/in/yeddula-jagadeesh-9b2365324/',
  },
];

export default MENTORS;
