/** Local logos already in marketing public assets. */
export const LOGO = {
  python: '/wp-content/uploads/2026/07/python-logo.svg',
  sql: '/wp-content/uploads/2024/03/sql-server-150x150-1.png',
  tensorflow: '/wp-content/uploads/2026/07/tensorflow-logo.svg',
  powerbi: '/wp-content/uploads/2024/03/power-bi-vector-logo-small.png',
  pandas: '/wp-content/uploads/2026/07/pandas-logo.svg',
  react: '/wp-content/uploads/2026/07/react-logo.svg',
  node: '/wp-content/uploads/2026/07/nodejs-logo.svg',
  express: '/wp-content/uploads/2026/07/express-logo.svg',
  mongo: '/wp-content/uploads/2026/07/mongodb-logo.svg',
  linux: '/wp-content/uploads/2026/07/linux-logo.svg',
  jupyter: '/wp-content/uploads/2026/07/jupyter-logo.svg',
  aws: '/wp-content/uploads/2024/03/awsss-1.png',
  java: '/wp-content/uploads/2026/07/java-logo.svg',
  spring: '/wp-content/uploads/2026/07/spring-logo.svg',
  django: '/wp-content/uploads/2026/07/django-logo.svg',
};


/** Soft-skill / method pictograms. */
const lucide = (name) =>
  `https://cdn.jsdelivr.net/npm/lucide-static@0.469.0/icons/${name}.svg`;

/**
 * Brand / well-known tech → local LOGO where available, else Lucide.
 * Soft-skill / method labels → Lucide icons.
 */
const TOOL_LOGO_BY_NAME = {
  Python: LOGO.python,
  Pandas: LOGO.pandas,
  Jupyter: LOGO.jupyter,
  TensorFlow: LOGO.tensorflow,
  SQL: LOGO.sql,
  'Power BI': LOGO.powerbi,
  React: LOGO.react,
  'Node.js': LOGO.node,
  Linux: LOGO.linux,
  AWS: LOGO.aws,
  'AWS Fundamentals': LOGO.aws,
  'AWS SageMaker': LOGO.aws,

  Docker: lucide('container'),
  Kubernetes: lucide('boxes'),
  Terraform: lucide('boxes'),
  Ansible: lucide('settings'),
  Jenkins: lucide('cog'),
  'GitHub Actions': lucide('git-branch'),
  'GitLab CI': lucide('git-branch'),
  'Argo CD': lucide('rocket'),
  Helm: lucide('anchor'),
  Prometheus: lucide('activity'),
  Grafana: lucide('line-chart'),
  'Microsoft Azure': lucide('cloud'),
  'Google Cloud': lucide('cloud'),
  'Google BigQuery': lucide('cloud'),
  'Azure ML': lucide('cloud'),
  'CloudFormation / Bicep': lucide('cloud'),
  'IAM / Entra ID': lucide('key-round'),
  'IAM / MFA': lucide('key-round'),
  FinOps: lucide('wallet'),
  MLflow: lucide('workflow'),
  PyTorch: lucide('brain'),
  'scikit-learn': lucide('brain'),
  'OpenAI / LLMs': lucide('sparkles'),
  'LangChain / RAG': lucide('link'),
  'ChatGPT / Copilot': lucide('sparkles'),
  Tableau: lucide('bar-chart-3'),
  'Looker / Looker Studio': lucide('bar-chart-3'),
  Excel: lucide('table'),
  'Excel / Google Sheets': lucide('table'),
  'Excel / Sheets': lucide('table'),
  Java: LOGO.java,
  'Spring Boot': LOGO.spring,
  Spring: LOGO.spring,
  Django: LOGO.django,
  FastAPI: lucide('zap'),
  'Git / GitHub': lucide('git-branch'),
  Confluence: lucide('file-text'),
  'Confluence / Notion': lucide('notebook'),
  'Jira / Azure Boards': lucide('kanban'),
  'Jira / Boards': lucide('kanban'),
  'Postman / APIs': lucide('send'),
  LinkedIn: lucide('briefcase'),
  'Slack / Teams': lucide('message-square'),
  'Miro / FigJam': lucide('layout'),
  Wireshark: lucide('radar'),
  'OWASP ZAP': lucide('shield'),
  'Burp Suite': lucide('shield-alert'),
  Nmap: lucide('scan-search'),
  'SIEM (Splunk / Sentinel)': lucide('search'),
  'Crowdstrike / EDR': lucide('shield'),
  'Nessus / Qualys': lucide('shield-check'),
  'ISO 27001 / SOC 2': lucide('badge-check'),
  'ISO / SOC Themes': lucide('badge-check'),
  Scrum: lucide('refresh-cw'),
  'Scrum / Kanban': lucide('refresh-cw'),
  Kanban: lucide('kanban'),
  'SAFe Awareness': lucide('layers'),
  'LMS / Moodle / Canvas': lucide('graduation-cap'),
  'MS Project / Planner': lucide('layout'),
  Statistics: lucide('sigma'),
  'LeetCode-style Platforms': lucide('code-2'),
  'LeetCode-style Practice': lucide('code-2'),
  'amazonec2': lucide('server'),

  // Soft skills / methods / L&D
  '1:1 Frameworks': lucide('users'),
  '360 Insights': lucide('radar'),
  'AI / GenAI Tracks': lucide('sparkles'),
  'AI Teaching Assist': lucide('bot'),
  'Accessibility Checks': lucide('accessibility'),
  'Accounting Basics': lucide('calculator'),
  'Action Learning': lucide('lightbulb'),
  'Active Learning Kits': lucide('puzzle'),
  'Activity Design Cards': lucide('layout-grid'),
  'Adult Learning Models': lucide('graduation-cap'),
  'Agile Delivery': lucide('refresh-cw'),
  'Analytics Dashboards': lucide('layout-dashboard'),
  'Aptitude Banks': lucide('brain'),
  'Assessment Builder': lucide('clipboard-list'),
  'Assessment Design': lucide('clipboard-check'),
  'Assessment Platform': lucide('shield-check'),
  'Audit Trails': lucide('file-search'),
  'Blended Models': lucide('layers'),
  'BoS Document Kits': lucide('folder-open'),
  'Board Pack Structures': lucide('briefcase'),
  'Budget Models': lucide('wallet'),
  'Burndown / CFD': lucide('trending-down'),
  'Business Writing': lucide('pen-line'),
  'Business Writing Models': lucide('file-edit'),
  'CRM / ERP Lenses': lucide('building-2'),
  'Cascade Playbooks': lucide('git-branch'),
  'Case Frameworks': lucide('scale'),
  'Certificate Engine': lucide('award'),
  'Certification Criteria': lucide('badge-check'),
  'Change Models': lucide('refresh-cw'),
  'Change Models (ADKAR etc.)': lucide('refresh-cw'),
  'Change Sponsorship': lucide('flag'),
  'Charter Templates': lucide('file-text'),
  'Cloud Tracks': lucide('cloud'),
  'Coaching Models': lucide('message-circle'),
  'Coding Assessments': lucide('code-2'),
  'Communication Cascades': lucide('megaphone'),
  'Company Research Sheets': lucide('search'),
  'Competency Frameworks': lucide('network'),
  'Content Creation': lucide('film'),
  'Credit Planning': lucide('calendar'),
  'Crisis Playbooks': lucide('alert-triangle'),
  'Curriculum Maps': lucide('map'),
  'Customer Journey Maps': lucide('route'),
  'Data Modelling': lucide('database'),
  'Decision Forums': lucide('messages-square'),
  'Demo Day Kits': lucide('presentation'),
  'Demo Day Rubrics': lucide('list-checks'),
  'Department Playbooks': lucide('book-open'),
  'Detection Awareness': lucide('eye'),
  'DevOps Tracks': lucide('cog'),
  'DoR / DoD': lucide('check-circle'),
  'EQ Frameworks': lucide('heart-handshake'),
  'Employer Brief Kits': lucide('building'),
  'Ethics Checklists': lucide('shield'),
  'Evaluation Rubrics': lucide('list-ordered'),
  'Executive Coaching': lucide('user-cog'),
  'Feedback Frameworks': lucide('message-square'),
  'Feedback Models': lucide('messages-square'),
  'Finance Caselets': lucide('dollar-sign'),
  'Financial Statements': lucide('file-spreadsheet'),
  'Funnel Analytics': lucide('filter'),
  'GD Rubrics': lucide('users'),
  'GROW Coaching': lucide('leaf'),
  'Grant Templates': lucide('file-plus'),
  'HiPo Assessment Inputs': lucide('trophy'),
  'Hybrid Class Tooling': lucide('monitor'),
  'Incident Logs': lucide('clipboard'),
  'Industry Advisory Inputs': lucide('handshake'),
  'InfoSec Awareness': lucide('shield-alert'),
  'Integrity Guidelines': lucide('scroll-text'),
  'Integrity Policies': lucide('gavel'),
  'Interview Panels': lucide('mic'),
  'Issue Trees': lucide('git-fork'),
  'Item Banks': lucide('library'),
  'LMS / LXP': lucide('monitor-play'),
  'LMS Completions': lucide('circle-check'),
  'LMS Integration': lucide('plug'),
  'LMS Progress': lucide('line-chart'),
  'Lab Design Guides': lucide('flask-conical'),
  'Lab Notebooks': lucide('notebook'),
  'Learning Analytics': lucide('bar-chart-3'),
  'Manager Dashboards': lucide('layout-dashboard'),
  'Market Research Basics': lucide('scan-search'),
  'Meeting Cadences': lucide('calendar-clock'),
  'Meeting Design': lucide('calendar'),
  'Mentor Checklists': lucide('list-todo'),
  'Mentor Ops': lucide('user-check'),
  'Mock Interview Scorecards': lucide('clipboard'),
  'OBE Frameworks': lucide('target'),
  'OBE Templates': lucide('layout'),
  'OKR / KPI Frameworks': lucide('target'),
  'OKR / Scorecards': lucide('gauge'),
  'OKR Cascades': lucide('network'),
  'OKR Literacy': lucide('bookmark'),
  'Observation Rubrics': lucide('search'),
  'Operating Model Canvases': lucide('git-merge'),
  'Peer Coaching': lucide('users'),
  'Peer Councils': lucide('users'),
  'Peer Observation': lucide('eye'),
  'Peer Review Rubrics': lucide('file-check'),
  'Performance Dialogues': lucide('message-square'),
  'Performance Systems': lucide('activity'),
  'Pilot Metrics': lucide('line-chart'),
  'Pitch Decks': lucide('presentation'),
  'Placement CRM / Sheets': lucide('contact'),
  'Planning Poker': lucide('hash'),
  'Policy Portals': lucide('globe'),
  'Portfolio Governance': lucide('briefcase'),
  'Presentation Design': lucide('projector'),
  'Presentation Frameworks': lucide('presentation'),
  'Presentation Packs': lucide('files'),
  'Privacy Frameworks': lucide('lock'),
  'Process Mapping': lucide('git-commit'),
  Proctoring: lucide('scan-face'),
  'Prompt Libraries': lucide('library'),
  'Prototype Kits': lucide('box'),
  'Psychometrics Basics': lucide('brain'),
  'Quiz Assist': lucide('help-circle'),
  RACI: lucide('table'),
  'RACI / DACI': lucide('table'),
  'RAID Logs': lucide('list'),
  'ROI / Kirkpatrick Lenses': lucide('pie-chart'),
  'RPA Awareness': lucide('bot'),
  'Ratio Frameworks': lucide('percent'),
  'Re-cert Cycles': lucide('rotate-cw'),
  'Readiness Scorecards': lucide('clipboard-check'),
  'Reference Managers': lucide('book'),
  'Remediation Paths': lucide('route'),
  'Resume ATS Checks': lucide('file-search'),
  'Risk Appetite Tools': lucide('shield'),
  'Risk Matrices': lucide('grid-3x3'),
  'Rubric Design': lucide('list-checks'),
  'Rubric Generators': lucide('sparkles'),
  'Rubric Libraries': lucide('books'),
  'Rubric Scoring': lucide('star'),
  'SBI Feedback': lucide('message-circle'),
  'STAR Framework': lucide('star'),
  'STAR Interviews': lucide('mic'),
  'STAR Method': lucide('star'),
  'Scenario Assessments': lucide('users'),
  'Scenario Planning': lucide('map'),
  'Scheduling Tools': lucide('calendar-days'),
  'Season Playbooks': lucide('book'),
  'Session Timers': lucide('timer'),
  'Skill Assessments': lucide('badge-check'),
  'Skill Taxonomies': lucide('tags'),
  'Slide Assist': lucide('layout'),
  'Stack Labs (custom)': lucide('cpu'),
  'Stakeholder Maps': lucide('share-2'),
  'Story Mapping': lucide('map'),
  Storyboarding: lucide('images'),
  'Strategy Frameworks': lucide('compass'),
  'Survey / Stats Tools': lucide('clipboard-list'),
  'Syllabus Builders': lucide('list'),
  'Trainer Kits': lucide('backpack'),
  'Value Stream Mapping': lucide('git-merge'),
  'Variance Analysis': lucide('diff'),
  'Video Practice Labs': lucide('video'),
  'Virtual Facilitation': lucide('monitor'),
  'Weekly Log Formats': lucide('notebook'),
  'Whistleblower Awareness': lucide('megaphone'),
};

function fallbackLogo(name) {
  const lower = name.toLowerCase();
  if (lower.includes('aws')) return LOGO.aws;
  if (lower.includes('azure')) return lucide('cloud');
  if (lower.includes('python')) return LOGO.python;
  if (lower.includes('sql')) return LOGO.sql;
  if (lower.includes('power bi') || lower.includes('powerbi')) return LOGO.powerbi;
  if (lower.includes('entra') || lower.includes('iam')) return lucide('key-round');
  if (lower.includes('finops')) return lucide('wallet');
  if (lower.includes('cloudformation') || lower.includes('bicep')) return lucide('cloud');
  if (lower.includes('cloud')) return lucide('cloud');
  if (lower.includes('security') || lower.includes('secure') || lower.includes('infosec')) return lucide('shield');
  if (lower.includes('agile') || lower.includes('scrum')) return lucide('refresh-cw');
  if (lower.includes('lead') || lower.includes('coach') || lower.includes('mentor')) return lucide('users');
  if (lower.includes('assess') || lower.includes('quiz') || lower.includes('test')) return lucide('clipboard-check');
  if (lower.includes('dashboard') || lower.includes('analytic') || lower.includes('metric')) return lucide('bar-chart-3');
  if (lower.includes('ai') || lower.includes('genai') || lower.includes('llm')) return lucide('sparkles');
  if (lower.includes('excel') || lower.includes('sheet')) return lucide('table');
  if (lower.includes('git')) return lucide('git-branch');
  if (lower.includes('docker')) return lucide('container');
  if (lower.includes('kubernetes') || lower.includes('k8s')) return lucide('boxes');
  return lucide('badge-check');
}

export function resolveToolLogo(name) {
  return TOOL_LOGO_BY_NAME[name] || fallbackLogo(name);
}

/** Build tools list — always includes an image/logo. */
export const tool = (name, image) => ({
  name,
  image: image || resolveToolLogo(name),
});
