const homeProgramCards = [
  {
    id: 'data-engineering',
    title: 'Master in Data Engineering',
    href: '/courses/data-engineering-course-bangalore',
    image: '/wp-content/uploads/2026/07/corporate-benefits-laptop-team.jpg',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Build production pipelines with Python, SQL, and cloud platforms.',
  },
  {
    id: 'data-analytics',
    title: 'Master in Data Analytics',
    href: '/courses/data-analytics-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Analyze business data with Excel, SQL, Python, and Power BI.',
  },
  {
    id: 'pyspark',
    title: 'Master in PySpark',
    href: '/courses/pyspark-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Process large datasets with Apache Spark, Spark SQL, and ETL pipelines.',
  },
  {
    id: 'databricks-data-engineering',
    title: 'Master in Databricks Data Engineering',
    href: '/courses/databricks-data-engineering-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Lakehouse pipelines with Databricks, PySpark, Delta Lake, and Unity Catalog.',
  },
  {
    id: 'microsoft-fabric-data-engineering',
    title: 'Master in Microsoft Fabric Data Engineering',
    href: '/courses/microsoft-fabric-data-engineering-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Fabric pipelines with OneLake, Lakehouse, PySpark, Data Factory, and Power BI.',
  },
  {
    id: 'tableau',
    title: 'Master in Tableau',
    href: '/courses/tableau-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build BI dashboards with Tableau Desktop, Tableau Prep, SQL, and Excel.',
  },
  {
    id: 'advanced-excel',
    title: 'Master in Advanced Excel',
    href: '/courses/advanced-excel-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Excel dashboards with formulas, Pivot Tables, Power Query, and Power Pivot.',
  },
  {
    id: 'sql-bootcamp',
    title: 'Master in SQL Bootcamp',
    href: '/courses/sql-bootcamp-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: 'Intensive Bootcamp',
    benefit: '100% Job Assistance',
    summary: 'Write SQL queries, joins, CTEs, and window functions for real-world analytics.',
  },
  {
    id: 'python-bootcamp',
    title: 'Master in Python Bootcamp',
    href: '/courses/python-bootcamp-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: 'Intensive Bootcamp',
    benefit: '100% Job Assistance',
    summary: 'Write Python programs with OOP, Pandas, APIs, SQL, automation, and analytics.',
  },
  {
    id: 'full-stack-mern',
    title: 'Master in MERN Full Stack',
    href: '/courses/mern-full-stack-course-bangalore',
    image: '/wp-content/uploads/2024/03/Full-Stack-Development-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Build full-stack apps with MongoDB, Express, React, and Node.js.',
  },
  {
    id: 'java-fullstack',
    title: 'Master in Java Full Stack',
    href: '/courses/java-full-stack-course-bangalore',
    image: '/wp-content/uploads/2024/03/Full-Stack-Development-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Build end-to-end apps with Core Java, Spring Boot, and React.',
  },
  {
    id: 'python-fullstack',
    title: 'Master in Python Full Stack',
    href: '/courses/python-full-stack-course-bangalore',
    image: '/wp-content/uploads/2024/03/Full-Stack-Development-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Build end-to-end apps with Python, Django or FastAPI, and React.',
  },
  {
    id: 'data-science',
    title: 'Master in Data Science',
    href: '/courses/data-science-course-bangalore',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '6 Months',
    benefit: '100% Job Assistance',
    summary: 'Turn data into insights with ML, analytics, and visualization.',
  },
];

export default homeProgramCards;
