const homeProgramCards = [
  {
    id: 'data-engineering',
    title: 'Master in Data Engineering',
    href: '/courses/data-engineering',
    image: '/wp-content/uploads/2026/07/corporate-benefits-laptop-team.jpg',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Build production pipelines with Python, SQL, and cloud platforms.',
  },
  {
    id: 'data-analytics',
    title: 'Master in Data Analytics',
    href: '/data-analytics-course',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Analyze business data with Excel, SQL, Python, and Power BI.',
  },
  {
    id: 'pyspark',
    title: 'Master in PySpark',
    href: '/pyspark-course',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Process large datasets with Apache Spark, Spark SQL, and ETL pipelines.',
  },
  {
    id: 'databricks-data-engineering',
    title: 'Master in Databricks Data Engineering',
    href: '/databricks-data-engineering-course',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Lakehouse pipelines with Databricks, PySpark, Delta Lake, and Unity Catalog.',
  },
  {
    id: 'microsoft-fabric-data-engineering',
    title: 'Master in Microsoft Fabric Data Engineering',
    href: '/microsoft-fabric-data-engineering-course',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Fabric pipelines with OneLake, Lakehouse, PySpark, Data Factory, and Power BI.',
  },
  {
    id: 'tableau',
    title: 'Master in Tableau',
    href: '/tableau-course',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build BI dashboards with Tableau Desktop, Tableau Prep, SQL, and Excel.',
  },
  {
    id: 'advanced-excel',
    title: 'Master in Advanced Excel',
    href: '/advanced-excel-course',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '2 Months',
    benefit: '100% Job Assistance',
    summary: 'Build Excel dashboards with formulas, Pivot Tables, Power Query, and Power Pivot.',
  },
  {
    id: 'sql-bootcamp',
    title: 'Master in SQL Bootcamp',
    href: '/sql-bootcamp',
    image: '/wp-content/uploads/2024/03/Data-Engineering.png',
    duration: 'Intensive Bootcamp',
    benefit: '100% Job Assistance',
    summary: 'Write SQL queries, joins, CTEs, and window functions for real-world analytics.',
  },
  {
    id: 'python-bootcamp',
    title: 'Master in Python Bootcamp',
    href: '/python-bootcamp',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: 'Intensive Bootcamp',
    benefit: '100% Job Assistance',
    summary: 'Write Python programs with OOP, Pandas, APIs, SQL, automation, and analytics.',
  },
  {
    id: 'full-stack-mern',
    title: 'Master in Full Stack Development',
    href: '/mern-full-stack-development-course',
    image: '/wp-content/uploads/2024/03/Full-Stack-Development-1.png',
    duration: '3 Months',
    benefit: '100% Job Assistance',
    summary: 'Choose Java, Python, or MERN — ship end-to-end apps with mentorship.',
  },
  {
    id: 'data-science',
    title: 'Master in Data Science',
    href: '/courses/data-science',
    image: '/wp-content/uploads/2024/03/Data-Science1-1.png',
    duration: '6 Months',
    benefit: '100% Job Assistance',
    summary: 'Turn data into insights with ML, analytics, and visualization.',
  },
];

export default homeProgramCards;
