/**
 * Advanced Excel — course structure (modules + topics).
 */

const advancedExcelCurriculum = [
  {
    title: 'Excel & Data Analytics Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Build a strong Excel and analytics foundation — workbook management, structured data, KPIs, and turning business questions into decisions.',
    topics: [
      'Excel Interface & Workbook Management',
      'Data Types & Spreadsheet Best Practices',
      'Structured Data & Excel Tables',
      'Data Organization & Formatting',
      'Sorting & Filtering',
      'Data Validation',
      'Conditional Formatting',
      'Named Ranges',
      'Business Metrics & KPIs',
      'Analytical Thinking',
      'Understanding Business Questions',
      'Data-Driven Decision Making',
    ],
  },
  {
    title: 'Advanced Excel Formulas & Functions',
    topicsLabel: 'Topics Covered',
    description:
      'Master nested formulas, conditional aggregations, text and date functions, error handling, and dynamic arrays.',
    topics: [
      'Formula Fundamentals',
      'Nested Formulas',
      'IF & IFS',
      'AND, OR & NOT',
      'SUM, SUMIF & SUMIFS',
      'COUNT, COUNTIF & COUNTIFS',
      'AVERAGEIF & AVERAGEIFS',
      'MINIFS & MAXIFS',
      'Text Functions',
      'Date & Time Functions',
      'ROUND, ROUNDUP & ROUNDDOWN',
      'IFERROR',
      'Dynamic Array Formulas',
      'UNIQUE',
      'FILTER',
      'SORT',
      'SEQUENCE',
    ],
  },
  {
    title: 'Advanced Lookup & Reference Functions',
    topicsLabel: 'Topics Covered',
    description:
      'Look up data across sheets with XLOOKUP, INDEX MATCH, multi-criteria lookups, and error-safe matching.',
    topics: [
      'XLOOKUP',
      'VLOOKUP',
      'HLOOKUP',
      'INDEX & MATCH',
      'XMATCH',
      'Two-Way Lookups',
      'Multiple-Criteria Lookups',
      'Exact & Approximate Matching',
      'Lookup Across Multiple Sheets',
      'Handling Lookup Errors',
      'Lookup Best Practices',
    ],
  },
  {
    title: 'Data Cleaning & Preparation',
    topicsLabel: 'Topics Covered',
    description:
      'Turn messy raw data into analysis-ready tables — duplicates, blanks, text cleanup, and field splits.',
    topics: [
      'Identifying Data Quality Issues',
      'Removing Duplicates',
      'Handling Blank & Missing Values',
      'TRIM & CLEAN',
      'Text Standardization',
      'Text to Columns',
      'Flash Fill',
      'Find & Replace',
      'Data Type Correction',
      'Splitting & Combining Fields',
      'Preparing Raw Data for Analysis',
    ],
  },
  {
    title: 'Pivot Tables & Pivot Charts',
    topicsLabel: 'Topics Covered',
    description:
      'Summarize and explore data with Pivot Tables, grouping, slicers, timelines, and interactive Pivot Charts.',
    topics: [
      'Creating Pivot Tables',
      'Rows, Columns, Values & Filters',
      'Grouping Data',
      'Date & Numeric Grouping',
      'Calculated Fields',
      'Sorting & Filtering Pivot Tables',
      'Slicers',
      'Timelines',
      'Pivot Charts',
      'Interactive Reporting',
      'Pivot Table Best Practices',
    ],
  },
  {
    title: 'Advanced Data Analysis',
    topicsLabel: 'Topics Covered',
    description:
      'Analyze trends, variance, contribution, and scenarios — including Goal Seek, Data Tables, and What-If tools.',
    topics: [
      'Trend Analysis',
      'Variance Analysis',
      'Percentage Analysis',
      'Contribution Analysis',
      'Ranking',
      'Running Totals',
      'Growth Analysis',
      'Scenario Analysis',
      'Forecasting Fundamentals',
      'Goal Seek',
      'Data Tables',
      'Scenario Manager',
      'What-If Analysis',
    ],
  },
  {
    title: 'Power Query for Excel',
    topicsLabel: 'Topics Covered',
    description:
      'Import, profile, clean, merge, and refresh data with reusable Power Query transformation workflows.',
    topics: [
      'Introduction to Power Query',
      'Connecting to Excel & CSV Files',
      'Importing Data',
      'Data Profiling',
      'Data Cleaning',
      'Changing Data Types',
      'Removing Duplicates & Errors',
      'Merge Queries',
      'Append Queries',
      'Pivot & Unpivot',
      'Conditional Columns',
      'Custom Columns',
      'Query Parameters',
      'Reusable Data Transformation Workflows',
      'Refreshing Queries',
    ],
  },
  {
    title: 'Data Modeling & Power Pivot',
    topicsLabel: 'Topics Covered',
    description:
      'Model related tables in Power Pivot — star schema, relationships, calculated columns, measures, and DAX fundamentals.',
    topics: [
      'Data Modeling Fundamentals',
      'Tables & Relationships',
      'Fact & Dimension Tables',
      'Star Schema Concepts',
      'Power Pivot',
      'Excel Data Model',
      'Relationships',
      'Calculated Columns',
      'Measures',
      'DAX Fundamentals',
      'Data Model Optimization',
    ],
  },
  {
    title: 'Advanced Excel Dashboards & Data Visualization',
    topicsLabel: 'Topics Covered',
    description:
      'Plan and build professional interactive dashboards — charts, KPI cards, slicers, layout, and data storytelling.',
    topics: [
      'Dashboard Planning',
      'Choosing the Right Chart',
      'Column & Bar Charts',
      'Line & Area Charts',
      'Combo Charts',
      'Scatter Plots',
      'Waterfall Charts',
      'Funnel Charts',
      'KPI Cards',
      'Sparklines',
      'Interactive Dashboards',
      'Dynamic Charts',
      'Slicers & Controls',
      'Dashboard Layout',
      'Executive Reporting',
      'Professional Dashboard Design',
      'Data Storytelling',
    ],
  },
  {
    title: 'Excel Automation & Productivity',
    topicsLabel: 'Topics Covered',
    description:
      'Work faster with templates, named ranges, macros, basic VBA, and workbook protection best practices.',
    topics: [
      'Excel Productivity Techniques',
      'Reusable Templates',
      'Advanced Named Ranges',
      'Introduction to Macros',
      'Recording Macros',
      'Editing Basic VBA Macros',
      'Automating Repetitive Tasks',
      'Button-Based Automation',
      'Workbook & Worksheet Management',
      'Workbook Protection',
      'Automation Best Practices',
    ],
  },
  {
    title: 'Real-World Business Analytics Projects',
    topicsLabel: 'Topics Covered',
    description:
      'Practice the full analytics workflow: Business Requirement → Data Collection → Data Cleaning → Data Transformation → Analysis → Dashboard → Business Insights.',
    topics: [
      'Sales Analytics',
      'Finance Analytics',
      'HR Analytics',
      'Marketing Analytics',
      'Operations Analytics',
      'Inventory Analytics',
      'Customer Analytics',
      'Management Reporting',
      'Business KPI Reporting',
    ],
  },
  {
    title: 'Industry Capstone Project',
    topicsLabel: 'Topics Covered',
    description:
      'Build an end-to-end Advanced Excel Business Analytics solution using Raw Data → Power Query → Data Cleaning → Excel Analysis → Pivot Tables → Power Pivot → Dashboard → Business Insights.',
    topics: [
      'Business Requirement Analysis',
      'Raw Data Collection',
      'Data Cleaning',
      'Data Transformation',
      'Advanced Excel Formulas',
      'Power Query',
      'Pivot Table Analysis',
      'Data Modeling',
      'KPI Development',
      'Dashboard Development',
      'Business Insights',
      'Management-Ready Presentation',
    ],
  },
];

export default advancedExcelCurriculum;
