/**
 * Data Analytics — course structure (modules + topics).
 */

const dataAnalyticsCurriculum = [
  {
    title: 'Excel for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Build spreadsheet fluency for analytics — formulas, lookups, Pivot Tables, data cleaning, and Excel dashboards.',
    topics: [
      'Excel Fundamentals',
      'Data Entry & Data Management',
      'Formatting & Data Organization',
      'Basic & Advanced Formulas',
      'IF, IFS & Logical Functions',
      'Lookup Functions',
      'XLOOKUP & INDEX-MATCH',
      'Text & Date Functions',
      'Conditional Formatting',
      'Data Validation',
      'Sorting & Filtering',
      'Excel Tables',
      'Pivot Tables',
      'Pivot Charts',
      'Data Cleaning in Excel',
      'Advanced Excel Techniques',
      'Excel Dashboards',
    ],
  },
  {
    title: 'SQL for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Query and shape relational data with SQL — filters, joins, aggregations, window functions, and analysis-ready datasets.',
    topics: [
      'SQL Fundamentals',
      'Database Fundamentals',
      'SELECT Statements',
      'Filtering & Sorting',
      'Aggregate Functions',
      'GROUP BY & HAVING',
      'Joins',
      'Subqueries',
      'Common Table Expressions',
      'CASE Statements',
      'Window Functions',
      'Date & Time Functions',
      'String Functions',
      'Data Manipulation',
      'Data Cleaning with SQL',
      'Database Relationships',
      'Query Optimization Basics',
    ],
  },
  {
    title: 'Python for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Learn Python for analytical workflows — language fundamentals, data structures, files, and working with CSV and Excel data.',
    topics: [
      'Python Fundamentals',
      'Variables & Data Types',
      'Operators & Expressions',
      'Conditional Statements',
      'Loops',
      'Functions',
      'Lists, Tuples, Sets & Dictionaries',
      'File Handling',
      'Exception Handling',
      'Modules & Packages',
      'Object-Oriented Programming Basics',
      'Working with CSV & Excel Files',
      'Python for Data Analysis',
    ],
  },
  {
    title: 'Pandas & Data Manipulation',
    topicsLabel: 'Topics Covered',
    description:
      'Clean, transform, and analyze tabular data with Pandas — DataFrames, missing values, GroupBy, merges, and exports.',
    topics: [
      'Introduction to Pandas',
      'Series & DataFrames',
      'Importing Data',
      'Data Selection & Filtering',
      'Data Cleaning',
      'Handling Missing Values',
      'Removing Duplicates',
      'Data Transformation',
      'Sorting & Ranking',
      'GroupBy Operations',
      'Merging & Joining Data',
      'Reshaping Data',
      'Aggregation',
      'Date & Time Analysis',
      'Exporting Data',
    ],
  },
  {
    title: 'Statistics for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Use statistics to interpret data — descriptive measures, distributions, correlation, sampling, and business-facing interpretation.',
    topics: [
      'Statistics Fundamentals',
      'Descriptive Statistics',
      'Mean, Median & Mode',
      'Range & Variance',
      'Standard Deviation',
      'Percentiles & Quartiles',
      'Probability Basics',
      'Distributions',
      'Correlation',
      'Covariance',
      'Sampling',
      'Hypothesis Testing Basics',
      'Statistical Interpretation',
      'Business Applications of Statistics',
    ],
  },
  {
    title: 'Data Visualization',
    topicsLabel: 'Topics Covered',
    description:
      'Choose the right charts and tell a clear data story — KPIs, trends, comparisons, dashboard design, and presenting insights.',
    topics: [
      'Data Visualization Fundamentals',
      'Choosing the Right Chart',
      'Bar Charts',
      'Line Charts',
      'Pie & Donut Charts',
      'Scatter Plots',
      'Histograms',
      'Box Plots',
      'Trend Analysis',
      'Comparative Analysis',
      'Distribution Analysis',
      'KPI Visualization',
      'Dashboard Design Principles',
      'Data Storytelling',
      'Presenting Insights',
    ],
  },
  {
    title: 'Power BI',
    topicsLabel: 'Topics Covered',
    description:
      'Build interactive reports in Power BI — Power Query, data modeling, DAX, visuals, and publishing dashboards.',
    topics: [
      'Power BI Fundamentals',
      'Power BI Desktop',
      'Connecting Data Sources',
      'Data Import & Transformation',
      'Power Query',
      'Data Cleaning',
      'Data Modeling',
      'Relationships',
      'Calculated Columns',
      'Measures',
      'DAX Fundamentals',
      'DAX Functions',
      'Filters & Slicers',
      'Interactive Visualizations',
      'Drill-Down & Drill-Through',
      'Dashboard Development',
      'Report Design',
      'Power BI Service',
      'Publishing & Sharing Reports',
    ],
  },
  {
    title: 'Business Analytics & Problem Solving',
    topicsLabel: 'Topics Covered',
    description:
      'Connect analysis to business decisions — KPIs, domain metrics, root-cause thinking, and actionable recommendations.',
    topics: [
      'Understanding Business Problems',
      'Defining Business KPIs',
      'Requirement Gathering',
      'Data-Driven Decision Making',
      'Business Metrics',
      'Sales Analytics',
      'Marketing Analytics',
      'Customer Analytics',
      'Financial Analytics',
      'Operations Analytics',
      'Trend Analysis',
      'Root Cause Analysis',
      'Performance Analysis',
      'Generating Actionable Insights',
      'Presenting Business Recommendations',
    ],
  },
  {
    title: 'Industry Capstone',
    topicsLabel: 'Topics Covered',
    description:
      'Deliver an end-to-end analytics project — from a business problem and data cleaning to SQL, Python, Power BI, insights, and a portfolio presentation.',
    topics: [
      'Business Problem Identification',
      'Data Collection',
      'Data Cleaning',
      'Exploratory Data Analysis',
      'SQL Analysis',
      'Python & Pandas Analysis',
      'Statistical Analysis',
      'Power BI Dashboard',
      'KPI Development',
      'Business Insights',
      'Data Storytelling',
      'Final Presentation',
      'Portfolio Development',
    ],
  },
];

export default dataAnalyticsCurriculum;
