/**
 * Python Full Stack — course structure (modules + topics).
 */

const fullStackPythonCurriculum = [
  {
    title: 'Frontend Development',
    topicsLabel: 'Topics Covered',
    description:
      'Build modern, responsive user interfaces with HTML5 and CSS3 — from page structure and styling to layouts, animation, and production-ready frontend practices.',
    groups: [
      {
        label: 'HTML5',
        items: [
          'Introduction to HTML',
          'HTML5 Fundamentals',
          'HTML Elements & Page Structure',
          'Links, Anchors & Navigation',
          'Multimedia & Embedded Content',
          'Frames & Iframes',
          'Advanced HTML Concepts',
          'HTML References',
        ],
      },
      {
        label: 'CSS3',
        items: [
          'CSS Fundamentals',
          'CSS Selectors',
          'CSS Units',
          'Typography & Text Styling',
          'Box Model',
          'Colors & Backgrounds',
          'CSS Layouts',
          'Animations & Transitions',
          'Responsive Web Design',
          'CSS Frameworks',
          'CSS Functions',
          'Specificity & Z-Index',
          'Opacity & Filters',
          'Image Sprites',
        ],
      },
    ],
  },
  {
    title: 'Programming with Python',
    topicsLabel: 'Topics Covered',
    description:
      'Develop strong Python programming skills for backend and full stack application development — from fundamentals to OOP, files, and database connectivity.',
    topics: [
      'Introduction to Python',
      'Python Built-in & Library Functions',
      'Variables & Data Types',
      'Operators & Expressions',
      'Input & Output',
      'Control Flow Statements',
      'Functions',
      'Lists, Sets & Dictionaries',
      'Comprehensions',
      'Lambda, map(), filter() & reduce()',
      'Modules & Packages',
      'File Handling',
      'Exception Handling',
      'Object-Oriented Programming',
      'Decorators, Iterators & Generators',
      'Regular Expressions',
      'SQL Database Connectivity',
      'Multithreading',
    ],
  },
  {
    title: 'JavaScript',
    topicsLabel: 'Topics Covered',
    description:
      'Learn JavaScript for interactive UIs — language fundamentals, the DOM, events, asynchronous programming, and browser storage.',
    topics: [
      'JavaScript Fundamentals',
      'JavaScript Files & Output Methods',
      'Variables & Constants',
      'Tokens & Operators',
      'Statements & Expressions',
      'Data Types & Type Conversion',
      'Primitive & Non-Primitive Data Types',
      'Hoisting',
      'Arrays & Objects',
      'JSON',
      'Shallow & Deep Copying',
      'this Keyword',
      'Prototypes & Prototype Methods',
      'Object-Oriented Programming',
      'ES6 Classes',
      'DOM Manipulation',
      'DOM Events & Event Propagation',
      'Asynchronous JavaScript',
      'Promises',
      'Browser Storage',
    ],
  },
  {
    title: 'SQL & Database Management',
    topicsLabel: 'Topics Covered',
    description:
      'Work with relational databases using SQL, then connect Python applications to store, query, and manage data.',
    groups: [
      {
        label: 'SQL',
        items: [
          'Introduction to SQL',
          'SQL Data Types',
          'Constraints',
          'SQL Statements',
          'Data Query Language (DQL)',
          'SQL Operators',
          'SQL Functions',
          'Grouping & Aggregate Functions',
          'Sorting & Ordering',
          'Subqueries',
          'Joins',
          'Correlated Subqueries',
          'Data Definition Language (DDL)',
          'Data Manipulation Language (DML)',
          'Transaction Control Language (TCL)',
          'Data Control Language (DCL)',
          'Database Normalization',
        ],
      },
      {
        label: 'Database Connectivity',
        items: [
          'Python & SQL Connectivity',
          'Database Queries',
          'Tables & Relationships',
          'Data Management',
        ],
      },
    ],
  },
  {
    title: 'Django & Backend Development',
    topicsLabel: 'Topics Covered',
    description:
      'Build Python backends with Django — projects, models, ORM, auth, forms, templates, and REST APIs.',
    topics: [
      'Introduction to Django',
      'Django Project & App Structure',
      'Getting Started with Django',
      'URL Routing & Navigation',
      'Views & Templates',
      'Static Files & Media',
      'Models & Databases',
      'Django ORM',
      'Django Admin Interface',
      'Forms & Validation',
      'User Authentication',
      'Authorization & Access Control',
      'RESTful Web Services',
      'REST API Development',
      'Advanced Django Concepts',
    ],
  },
  {
    title: 'Advanced Backend Development',
    topicsLabel: 'Topics Covered',
    description:
      'Deepen backend skills with API architecture, validation, security, testing, files, and performance basics.',
    topics: [
      'REST API Architecture',
      'API Development with Django',
      'Authentication & Authorization',
      'Form & API Validation',
      'Error & Exception Handling',
      'Database Integration',
      'File Handling & Media Management',
      'API Testing',
      'Application Security Basics',
      'Backend Performance Basics',
    ],
  },
  {
    title: 'Full Stack Integration',
    topicsLabel: 'Topics Covered',
    description:
      'Connect frontend, backend, and databases into complete applications — APIs, auth flows, and end-to-end architecture.',
    topics: [
      'Frontend & Backend Integration',
      'Connecting JavaScript with Django',
      'REST API Integration',
      'Database Integration',
      'User Authentication Flow',
      'Form & Data Handling',
      'Dynamic Web Application Development',
      'End-to-End Application Architecture',
    ],
  },
  {
    title: 'Git, GitHub & Deployment',
    topicsLabel: 'Topics Covered',
    description:
      'Version-control your work and ship applications with Git, GitHub, environment configuration, and production deployment basics.',
    topics: [
      'Git Fundamentals',
      'Repository Management',
      'Branching & Merging',
      'Version Control',
      'GitHub Workflow',
      'Code Collaboration',
      'Environment Variables',
      'Application Deployment',
      'Production Configuration',
      'Domain & SSL Basics',
    ],
  },
  {
    title: 'Industry Capstone Projects',
    topicsLabel: 'Topics Covered',
    description:
      'Apply the full stack in portfolio-ready projects — from Python and Django apps to REST APIs, auth, and production deployment.',
    topics: [
      'Python Application Development',
      'Django Web Application',
      'Database-Driven Application',
      'Frontend & Backend Integration',
      'REST API Integration',
      'Authentication & Authorization',
      'Full Stack Application Development',
      'Production-Ready Deployment',
      'GitHub Project Management',
    ],
  },
];

export default fullStackPythonCurriculum;
