/**
 * Java Full Stack — course structure (modules + topics).
 */

const fullStackJavaCurriculum = [
  {
    title: 'Core Java',
    topicsLabel: 'Topics Covered',
    description:
      'Build a strong Java programming foundation — from language basics and OOP to collections, Java 8 features, multithreading, and the Stream API.',
    topics: [
      'Introduction to Programming & Java',
      'Variables & Data Types',
      'Operators & Methods',
      'Decision-Making & Looping Statements',
      'Arrays & 2D Arrays',
      'Object-Oriented Programming Fundamentals',
      'OOP Concepts',
      'Encapsulation & Data Hiding',
      'Inheritance & Is-A Relationship',
      'Polymorphism',
      'Abstraction',
      'Composition & Has-A Relationship',
      'Object Class',
      'Strings & String Handling',
      'Exception & Exception Handling',
      'Wrapper Classes',
      'Java Collection Framework',
      'Java 8 Features',
      'Multithreading',
      'Functional Programming',
      'Stream API',
    ],
  },
  {
    title: 'JDBC & Database Connectivity',
    topicsLabel: 'Topics Covered',
    description:
      'Connect Java applications to relational databases with JDBC — statements, CRUD, batch execution, metadata, and connection pooling.',
    topics: [
      'Introduction to JDBC',
      'File vs Database',
      'JDBC API',
      'Steps to Connect Java with a Database',
      'Statement',
      'PreparedStatement',
      'Executing SQL Queries',
      'execute(), executeUpdate() & executeQuery()',
      'Batch Execution',
      'Maven Project Setup',
      'CRUD Operations using JDBC',
      'Stored Procedures',
      'Database Functions',
      'Database Metadata',
      'ResultSet Metadata',
      'Connection Pooling',
      'JDBC Database Connectivity Project',
    ],
  },
  {
    title: 'Hibernate with JPA',
    topicsLabel: 'Topics Covered',
    description:
      'Map Java objects to databases with Hibernate and JPA — entities, mappings, caching, and practical CRUD implementation.',
    topics: [
      'Introduction to Hibernate ORM Framework',
      'Hibernate & JPA Fundamentals',
      'Entity Class Creation Rules',
      'Hibernate CRUD Operations',
      'Primary Key & Composite Key',
      'Hibernate Mapping',
      'One-to-One Mapping',
      'One-to-Many Mapping',
      'Many-to-Many Mapping',
      'Unidirectional & Bidirectional Mapping',
      'Hibernate Annotations',
      'Cascade Types',
      'ID Generation Strategies',
      'First-Level Cache',
      'Second-Level Cache',
      'Hibernate Session & Lifecycle',
      'Hibernate & JPA Practical Implementation',
    ],
  },
  {
    title: 'Spring Framework & Spring Boot',
    topicsLabel: 'Topics Covered',
    description:
      'Build production-style backends with Spring Core, Spring Boot, REST APIs, Spring Security, and microservices fundamentals.',
    groups: [
      {
        label: 'Spring Core',
        items: [
          'Spring Framework Fundamentals',
          'Dependency Injection',
          'Inversion of Control',
          'Spring Beans & Configuration',
        ],
      },
      {
        label: 'Spring Boot',
        items: [
          'Introduction to Spring Boot',
          'Spring Boot Project Structure',
          'REST API Development',
          'Configuration & Properties',
          'Dependency Management',
        ],
      },
      {
        label: 'RESTful Web Services',
        items: [
          'REST Architecture',
          'HTTP Methods',
          'Request & Response Handling',
          'REST API Development',
        ],
      },
      {
        label: 'Spring Security',
        items: [
          'Authentication',
          'Authorization',
          'Security Configuration',
          'API Security',
        ],
      },
      {
        label: 'Microservices',
        items: [
          'Microservices Architecture',
          'Service-Based Application Design',
          'Inter-Service Communication',
          'Microservices Fundamentals',
        ],
      },
    ],
  },
  {
    title: 'Frontend Development',
    topicsLabel: 'Topics Covered',
    description:
      'Build modern, responsive user interfaces with HTML5 and CSS3 — from page structure and styling to layouts, animation, and production-ready frontend practices.',
    groups: [
      {
        label: 'HTML5',
        items: [
          'Introduction to HTML',
          'HTML5 Fundamentals',
          'HTML Elements & Page Structure',
          'Links, Anchors & Navigation',
          'Multimedia & Embedded Content',
          'Frames & Iframes',
          'Advanced HTML Concepts',
          'HTML References',
        ],
      },
      {
        label: 'CSS3',
        items: [
          'CSS Fundamentals',
          'CSS Selectors',
          'CSS Units',
          'Typography & Text Styling',
          'Box Model',
          'Colors & Backgrounds',
          'CSS Layouts',
          'Animations & Transitions',
          'Responsive Web Design',
          'CSS Frameworks',
          'Lists & Tables',
          'CSS Functions',
          'Specificity & Z-Index',
          'Opacity & Filters',
          'Image Sprites',
          'CSS Entities',
        ],
      },
    ],
  },
  {
    title: 'JavaScript',
    topicsLabel: 'Topics Covered',
    description:
      'Learn JavaScript for interactive UIs — language fundamentals, the DOM, events, asynchronous programming, and browser storage.',
    topics: [
      'JavaScript Fundamentals',
      'JavaScript Files & Integration',
      'Output Methods',
      'Variables & Constants',
      'JavaScript Tokens',
      'Hoisting',
      'Operators',
      'Statements & Expressions',
      'Data Types',
      'Type Casting & Type Conversion',
      'Primitive & Non-Primitive Data Types',
      'JSON',
      'Shallow & Deep Copying',
      'this Keyword',
      'Prototypes',
      'Function & Prototype Methods',
      'Object-Oriented Programming',
      'ES6 Classes',
      'Asynchronous JavaScript',
      'Promises',
      'Browser Storage',
      'DOM Manipulation',
      'DOM Events',
      'Event Propagation',
    ],
  },
  {
    title: 'SQL & Database Management',
    topicsLabel: 'Topics Covered',
    description:
      'Work with relational databases using SQL — queries, joins, constraints, transactions, and database normalization.',
    topics: [
      'Introduction to SQL',
      'SQL Data Types',
      'Constraints',
      'SQL Statements',
      'Data Query Language (DQL)',
      'SQL Operators',
      'SQL Functions',
      'Grouping & Aggregate Functions',
      'Sorting & Ordering',
      'Subqueries',
      'SQL Joins',
      'Correlated Subqueries',
      'Data Definition Language (DDL)',
      'Data Manipulation Language (DML)',
      'Transaction Control Language (TCL)',
      'Data Control Language (DCL)',
      'Database Normalization',
    ],
  },
  {
    title: 'Industry Capstone Projects',
    topicsLabel: 'Topics Covered',
    description:
      'Apply the full stack in portfolio-ready projects — from Core Java and JDBC apps to Spring Boot APIs, auth, and production-ready applications.',
    topics: [
      'Core Java Application Development',
      'JDBC CRUD Application',
      'Hibernate & JPA Database Application',
      'Spring Boot REST API',
      'Spring Security Implementation',
      'Full Stack Frontend & Backend Integration',
      'Database Integration',
      'Authentication & Authorization',
      'Production-Ready Full Stack Application',
    ],
  },
];

export default fullStackJavaCurriculum;
