/**
 * Microsoft Fabric Data Engineering — course structure (modules + topics).
 */

const microsoftFabricDataEngineeringCurriculum = [
  {
    title: 'Data Engineering Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Build a foundation in modern data engineering — ETL/ELT, ingestion, pipelines, and Lakehouse concepts.',
    topics: [
      'Data Engineering Fundamentals',
      'Modern Data Engineering Concepts',
      'ETL & ELT',
      'Data Ingestion',
      'Data Transformation',
      'Data Pipelines',
      'Structured & Unstructured Data',
      'Batch Data Processing',
      'Data Integration',
      'Data Architecture Fundamentals',
      'Modern Lakehouse Concepts',
    ],
  },
  {
    title: 'Python & SQL for Data Engineering',
    topicsLabel: 'Topics Covered',
    description:
      'Use Python and SQL as the working languages of data engineering — processing, queries, joins, and transformations.',
    groups: [
      {
        label: 'Python',
        items: [
          'Python Fundamentals',
          'Variables & Data Types',
          'Data Structures',
          'Functions',
          'File Handling',
          'Exception Handling',
          'Modules & Packages',
          'Lambda Functions',
          'Python for Data Processing',
          'Pandas Fundamentals',
        ],
      },
      {
        label: 'SQL',
        items: [
          'SQL Fundamentals',
          'SELECT Queries',
          'Filtering & Sorting',
          'Joins',
          'Aggregate Functions',
          'GROUP BY & HAVING',
          'Subqueries',
          'CASE Statements',
          'Window Functions',
          'Data Transformation with SQL',
        ],
      },
    ],
  },
  {
    title: 'Apache Spark & PySpark',
    topicsLabel: 'Topics Covered',
    description:
      'Process data at scale with Spark and PySpark — DataFrames, Spark SQL, transformations, and performance basics.',
    topics: [
      'Apache Spark Fundamentals',
      'Spark Architecture',
      'SparkSession',
      'Spark DataFrames',
      'RDD Fundamentals',
      'Transformations',
      'Actions',
      'Lazy Evaluation',
      'PySpark Data Processing',
      'Spark SQL',
      'Joins & Aggregations',
      'Window Functions',
      'Partitioning',
      'Spark Performance Basics',
    ],
  },
  {
    title: 'Microsoft Fabric Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Work in Microsoft Fabric — architecture, workspaces, items, experiences, capacity, and the Data Engineering experience.',
    topics: [
      'Introduction to Microsoft Fabric',
      'Fabric Architecture',
      'Fabric Workspaces',
      'Fabric Items',
      'Fabric Experiences',
      'Fabric Capacity Fundamentals',
      'Microsoft Fabric Portal',
      'Workspace Management',
      'Data Engineering Experience',
      'Fabric Data Lifecycle',
      'Working with Fabric Workloads',
    ],
  },
  {
    title: 'OneLake & Lakehouse',
    topicsLabel: 'Topics Covered',
    description:
      'Microsoft Fabric uses OneLake as its unified logical data lake, while Lakehouse provides Spark and SQL access to data stored in the platform.',
    groups: [
      {
        label: 'OneLake',
        items: [
          'OneLake Fundamentals',
          'Unified Data Lake Concepts',
          'Data Storage in OneLake',
          'OneLake Architecture',
          'OneLake Shortcuts',
          'External Data Access',
          'Data Sharing Concepts',
        ],
      },
      {
        label: 'Lakehouse',
        items: [
          'Lakehouse Fundamentals',
          'Creating a Lakehouse',
          'Lakehouse Explorer',
          'Files & Tables',
          'Delta Tables',
          'Lakehouse Data Management',
          'SQL Analytics Endpoint',
          'Spark & SQL Access',
          'Lakehouse Architecture',
        ],
      },
    ],
  },
  {
    title: 'Data Factory & Data Integration',
    topicsLabel: 'Topics Covered',
    description:
      'Fabric Data Factory supports data movement, transformation, and orchestration, including pipelines and Dataflow Gen2.',
    topics: [
      'Microsoft Fabric Data Factory',
      'Data Integration Fundamentals',
      'Data Sources & Connectors',
      'Copy Data',
      'Data Pipelines',
      'Pipeline Activities',
      'Pipeline Parameters',
      'Pipeline Variables',
      'Pipeline Scheduling',
      'Pipeline Triggers',
      'Data Transformation',
      'ETL & ELT Workflows',
      'Pipeline Monitoring',
    ],
  },
  {
    title: 'Dataflow Gen2 & Data Transformation',
    topicsLabel: 'Topics Covered',
    description:
      'Dataflow Gen2 provides a visual, low-code approach to ingesting and transforming data using Power Query.',
    topics: [
      'Dataflow Gen2 Fundamentals',
      'Power Query',
      'Connecting Data Sources',
      'Data Ingestion',
      'Data Cleaning',
      'Data Transformation',
      'Filtering',
      'Joins',
      'Aggregations',
      'Data Type Transformation',
      'Custom Transformations',
      'Loading Data into Lakehouse',
      'Dataflow Scheduling',
      'Dataflow Monitoring',
    ],
  },
  {
    title: 'Delta Lake & Medallion Architecture',
    topicsLabel: 'Topics Covered',
    description:
      'Store reliable lake data with Delta Lake and implement Bronze → Silver → Gold Medallion Architecture.',
    topics: [
      'Delta Lake Fundamentals',
      'Delta Tables',
      'ACID Transactions',
      'Schema Enforcement',
      'Schema Evolution',
      'Time Travel',
      'Data Versioning',
      'Delta Table Optimization',
      'Medallion Architecture',
      'Bronze Layer',
      'Silver Layer',
      'Gold Layer',
      'Data Quality',
      'Data Transformation Architecture',
    ],
  },
  {
    title: 'Fabric Warehouse, Governance & Analytics Integration',
    topicsLabel: 'Topics Covered',
    description:
      'Fabric Lakehouses automatically provide a SQL analytics endpoint for querying Delta tables and can connect directly with Power BI for reporting.',
    groups: [
      {
        label: 'Fabric Warehouse',
        items: [
          'Warehouse Fundamentals',
          'T-SQL Development',
          'Tables & Views',
          'Data Loading',
          'Data Modeling',
          'Querying Warehouse Data',
          'Lakehouse vs Warehouse',
          'SQL-Based Analytics',
        ],
      },
      {
        label: 'Governance',
        items: [
          'Data Governance Fundamentals',
          'Security & Access Control',
          'Permissions',
          'Workspace Governance',
          'Data Discovery',
          'Data Lineage',
          'Monitoring',
        ],
      },
      {
        label: 'Power BI Integration',
        items: [
          'Connecting Power BI to Fabric',
          'Semantic Models',
          'Power BI Reporting',
          'Data Visualization',
          'Business Intelligence Integration',
          'Building Reports from Fabric Data',
        ],
      },
    ],
  },
  {
    title: 'Advanced Fabric Data Engineering',
    topicsLabel: 'Topics Covered',
    description:
      'Build production-style Fabric pipelines — incremental processing, notebooks, Spark jobs, quality checks, and monitoring.',
    topics: [
      'End-to-End Data Pipelines',
      'Incremental Data Processing',
      'Pipeline Orchestration',
      'Notebook Integration',
      'Spark Job Processing',
      'Data Quality Checks',
      'Performance Optimization',
      'Pipeline Monitoring',
      'Error Handling',
      'Production Data Engineering',
      'Real-World Data Integration',
      'Cloud Data Sources',
      'External Data Integration',
    ],
  },
  {
    title: 'Industry Capstone Project',
    topicsLabel: 'Topics Covered',
    description:
      'Build an end-to-end Microsoft Fabric Data Engineering solution using OneLake → Lakehouse → PySpark → Data Factory → Dataflow Gen2 → Delta Lake → Power BI.',
    topics: [
      'Data Ingestion',
      'Data Transformation',
      'PySpark Processing',
      'SQL Analysis',
      'Lakehouse Development',
      'Bronze → Silver → Gold Architecture',
      'Data Factory Pipeline',
      'Dataflow Gen2',
      'Delta Lake Tables',
      'Pipeline Orchestration',
      'Data Quality',
      'Power BI Integration',
      'End-to-End Data Engineering',
    ],
  },
];

export default microsoftFabricDataEngineeringCurriculum;
