/**
 * PySpark — course structure (modules + topics).
 */

const pysparkCurriculum = [
  {
    title: 'Python for PySpark',
    topicsLabel: 'Topics Covered',
    description:
      'Build the Python foundation needed for PySpark — data structures, functions, files, lambdas, and data processing.',
    topics: [
      'Python Fundamentals',
      'Variables & Data Types',
      'Operators & Expressions',
      'Conditional Statements',
      'Loops',
      'Functions',
      'Lists, Tuples, Sets & Dictionaries',
      'Modules & Packages',
      'Exception Handling',
      'File Handling',
      'Object-Oriented Programming Basics',
      'Lambda Functions',
      'Iterators & Generators',
      'Working with CSV & JSON',
      'Python for Data Processing',
    ],
  },
  {
    title: 'Big Data & Apache Spark Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Understand distributed computing and Spark architecture — drivers, executors, jobs, stages, tasks, and cluster execution.',
    topics: [
      'Introduction to Big Data',
      'Big Data Characteristics',
      'Distributed Computing',
      'Hadoop & Big Data Ecosystem',
      'Apache Spark Overview',
      'Spark Architecture',
      'Driver & Executors',
      'Spark Cluster Components',
      'Spark Jobs, Stages & Tasks',
      'Spark Application Lifecycle',
      'Local & Cluster Execution',
    ],
  },
  {
    title: 'PySpark Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Work with SparkSession, SparkContext, and RDDs — transformations, actions, lazy evaluation, caching, and partitioning.',
    topics: [
      'Introduction to PySpark',
      'SparkSession',
      'SparkContext',
      'RDD Fundamentals',
      'Creating RDDs',
      'Transformations',
      'Actions',
      'Lazy Evaluation',
      'Narrow & Wide Transformations',
      'RDD Persistence',
      'Caching',
      'Partitioning',
      'Fault Tolerance',
    ],
  },
  {
    title: 'PySpark DataFrames',
    topicsLabel: 'Topics Covered',
    description:
      'Process structured data with DataFrames — schemas, filtering, aggregations, GroupBy, and window functions.',
    topics: [
      'DataFrame Fundamentals',
      'Creating DataFrames',
      'Reading Data',
      'Writing Data',
      'Schema Definition',
      'Data Types',
      'Selecting Columns',
      'Filtering Data',
      'Sorting Data',
      'Adding & Renaming Columns',
      'Handling Missing Values',
      'Removing Duplicates',
      'Data Type Conversion',
      'Aggregations',
      'GroupBy Operations',
      'Window Functions',
    ],
  },
  {
    title: 'Spark SQL',
    topicsLabel: 'Topics Covered',
    description:
      'Query Spark data with SQL — views, joins, aggregations, window functions, and SQL optimization basics.',
    topics: [
      'Spark SQL Fundamentals',
      'SQL Queries in Spark',
      'Creating Temporary Views',
      'SELECT Statements',
      'Filtering & Sorting',
      'GROUP BY',
      'Aggregate Functions',
      'Joins',
      'Subqueries',
      'CASE Statements',
      'Window Functions',
      'SQL & DataFrame API',
      'Query Execution',
      'SQL Optimization Basics',
    ],
  },
  {
    title: 'Data Processing & ETL with PySpark',
    topicsLabel: 'Topics Covered',
    description:
      'Build reusable ETL pipelines — extract, clean, validate, enrich, aggregate, and load large datasets.',
    topics: [
      'ETL Fundamentals',
      'Data Extraction',
      'Data Transformation',
      'Data Loading',
      'Batch Processing',
      'Data Cleaning',
      'Data Validation',
      'Handling Missing Data',
      'Duplicate Handling',
      'Data Standardization',
      'Data Aggregation',
      'Data Enrichment',
      'Incremental Data Processing',
      'File-Based Data Processing',
      'Building Reusable ETL Pipelines',
    ],
  },
  {
    title: 'Working with Big Data Formats',
    topicsLabel: 'Topics Covered',
    description:
      'Read and write large datasets in analytics-friendly formats — CSV, JSON, Parquet, ORC, partitioning, and data lakes.',
    topics: [
      'CSV Files',
      'JSON Files',
      'Parquet',
      'ORC',
      'Avro Basics',
      'Reading & Writing Large Datasets',
      'Partitioned Data',
      'Compression',
      'Schema Management',
      'File Optimization',
      'Data Lake Concepts',
    ],
  },
  {
    title: 'PySpark Performance Optimization',
    topicsLabel: 'Topics Covered',
    description:
      'Tune Spark jobs — DAGs, partitioning, caching, broadcast joins, shuffle, skew, Spark UI, and troubleshooting.',
    topics: [
      'Spark Execution Model',
      'Understanding DAGs',
      'Partitioning',
      'Repartition & Coalesce',
      'Caching & Persistence',
      'Broadcast Variables',
      'Broadcast Joins',
      'Shuffle Operations',
      'Handling Data Skew',
      'Join Optimization',
      'Serialization Basics',
      'Query Optimization',
      'Spark UI',
      'Performance Monitoring',
      'Troubleshooting Spark Jobs',
    ],
  },
  {
    title: 'Cloud & Data Engineering with PySpark',
    topicsLabel: 'Topics Covered',
    description:
      'Run Spark in the cloud — AWS, S3, data lakes, batch pipelines, and production data-processing workflows.',
    topics: [
      'Cloud Data Engineering Fundamentals',
      'AWS Overview',
      'Amazon S3',
      'Cloud-Based Data Processing',
      'Spark on Cloud',
      'Data Lake Architecture',
      'ETL Pipeline Architecture',
      'Batch Data Pipelines',
      'Cloud Storage Integration',
      'Data Processing Workflows',
      'Production Data Pipeline Concepts',
    ],
  },
  {
    title: 'Industry Capstone',
    topicsLabel: 'Topics Covered',
    description:
      'Deliver a production-style PySpark pipeline — ingestion, transformation, Spark SQL, optimization, cloud integration, and GitHub.',
    topics: [
      'Real-World Data Pipeline Development',
      'Large Dataset Processing',
      'Data Ingestion',
      'Data Cleaning & Transformation',
      'PySpark ETL Pipeline',
      'Spark SQL Analysis',
      'Data Lake Integration',
      'Performance Optimization',
      'Cloud Integration',
      'Pipeline Monitoring',
      'Production-Ready Data Processing',
      'GitHub Project Management',
    ],
  },
];

export default pysparkCurriculum;
