/**
 * Python Bootcamp — course structure (modules + topics).
 */

const pythonBootcampCurriculum = [
  {
    title: 'Programming & Python Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Set up Python and write your first programs — syntax, data types, operators, input/output, and debugging.',
    topics: [
      'Introduction to Programming',
      'What is Python?',
      'Python Installation & Environment Setup',
      'Python Syntax',
      'Variables & Constants',
      'Data Types',
      'Type Conversion',
      'Operators',
      'Input & Output',
      'Comments',
      'Basic Programming Logic',
      'Writing Your First Python Programs',
      'Debugging Fundamentals',
    ],
  },
  {
    title: 'Conditional Statements & Loops',
    topicsLabel: 'Topics Covered',
    description:
      'Control program flow with if/elif/else, comparison and logical operators, for/while loops, and pattern exercises.',
    topics: [
      'if Statements',
      'if-else',
      'elif',
      'Nested Conditions',
      'Comparison Operators',
      'Logical Operators',
      'for Loops',
      'while Loops',
      'Nested Loops',
      'break',
      'continue',
      'pass',
      'Range Function',
      'Pattern-Based Problems',
      'Practical Programming Exercises',
    ],
  },
  {
    title: 'Python Data Structures',
    topicsLabel: 'Topics Covered',
    description:
      'Work with lists, tuples, sets, and dictionaries — methods, operations, unpacking, and comprehensions.',
    groups: [
      {
        label: 'Lists',
        items: [
          'Creating Lists',
          'Indexing & Slicing',
          'List Methods',
          'List Operations',
          'List Comprehensions',
        ],
      },
      {
        label: 'Tuples',
        items: ['Tuple Operations', 'Tuple Methods', 'Tuple Unpacking'],
      },
      {
        label: 'Sets',
        items: ['Set Operations', 'Union', 'Intersection', 'Difference', 'Set Methods'],
      },
      {
        label: 'Dictionaries',
        items: [
          'Dictionary Operations',
          'Keys & Values',
          'Dictionary Methods',
          'Nested Dictionaries',
          'Dictionary Comprehensions',
        ],
      },
    ],
  },
  {
    title: 'Functions & Modular Programming',
    topicsLabel: 'Topics Covered',
    description:
      'Write reusable functions with args, kwargs, lambdas, map/filter/reduce, recursion, modules, and packages.',
    topics: [
      'Defining Functions',
      'Function Arguments',
      'Positional & Keyword Arguments',
      'Default Arguments',
      'Variable-Length Arguments',
      '*args & **kwargs',
      'Return Statements',
      'Scope of Variables',
      'Lambda Functions',
      'Map',
      'Filter',
      'Reduce',
      'Recursion',
      'Modules',
      'Packages',
      'Import Statements',
      'Creating Reusable Python Code',
    ],
  },
  {
    title: 'Strings & Advanced Python Operations',
    topicsLabel: 'Topics Covered',
    description:
      'Process text with string methods, f-strings, regular expressions, comprehensions, iterators, and generators.',
    topics: [
      'String Fundamentals',
      'String Indexing',
      'String Slicing',
      'String Methods',
      'String Formatting',
      'f-Strings',
      'Regular Expressions',
      'Pattern Matching',
      'List Comprehensions',
      'Dictionary Comprehensions',
      'Set Comprehensions',
      'Generator Expressions',
      'Iterators',
      'Generators',
    ],
  },
  {
    title: 'Object-Oriented Programming — OOP',
    topicsLabel: 'Topics Covered',
    description:
      'Model real-world problems with classes, inheritance, polymorphism, encapsulation, abstraction, and special methods.',
    topics: [
      'Introduction to OOP',
      'Classes & Objects',
      'Constructors',
      'Instance Variables',
      'Class Variables',
      'Methods',
      'Encapsulation',
      'Inheritance',
      'Single Inheritance',
      'Multiple Inheritance',
      'Multilevel Inheritance',
      'Polymorphism',
      'Method Overriding',
      'Abstraction',
      'Access Modifiers',
      'Special Methods',
      'Practical OOP Applications',
    ],
  },
  {
    title: 'Exception Handling & File Handling',
    topicsLabel: 'Topics Covered',
    description:
      'Handle errors safely and work with files, CSV, JSON, directories, and context managers.',
    topics: [
      'Exception Handling',
      'Errors vs Exceptions',
      'try',
      'except',
      'else',
      'finally',
      'Multiple Exceptions',
      'Custom Exceptions',
      'Raising Exceptions',
      'File Handling',
      'Opening Files',
      'Reading Files',
      'Writing Files',
      'Appending Data',
      'Working with CSV Files',
      'Working with JSON Files',
      'File & Directory Operations',
      'Context Managers',
    ],
  },
  {
    title: 'Python Libraries & Data Handling',
    topicsLabel: 'Topics Covered',
    description:
      'Use the standard library, NumPy, and Pandas to load, clean, filter, group, and transform tabular data.',
    topics: [
      'Python Standard Library',
      'NumPy Fundamentals',
      'Arrays',
      'Array Operations',
      'Pandas Fundamentals',
      'Series',
      'DataFrames',
      'Reading CSV & Excel Files',
      'Data Selection',
      'Filtering',
      'Sorting',
      'Grouping',
      'Aggregation',
      'Handling Missing Data',
      'Data Cleaning',
      'Data Transformation',
    ],
  },
  {
    title: 'Python & SQL Database Programming',
    topicsLabel: 'Topics Covered',
    description:
      'Connect Python to relational databases, run SQL, and build SQL + Python analytics workflows.',
    topics: [
      'Database Fundamentals',
      'SQL Fundamentals',
      'Connecting Python with Databases',
      'Database Connections',
      'Executing SQL Queries from Python',
      'INSERT, UPDATE & DELETE Operations',
      'Fetching Database Records',
      'Python Database Libraries',
      'Data Extraction',
      'Data Processing',
      'SQL + Python Analytics Workflows',
    ],
  },
  {
    title: 'APIs & Web Data',
    topicsLabel: 'Topics Covered',
    description:
      'Consume REST APIs with GET, POST, PUT, and DELETE — JSON, authentication, error handling, and integrations.',
    topics: [
      'Introduction to APIs',
      'REST APIs',
      'HTTP Methods',
      'GET',
      'POST',
      'PUT',
      'DELETE',
      'API Requests',
      'JSON Data',
      'Working with API Responses',
      'Authentication Fundamentals',
      'API Error Handling',
      'Consuming Public APIs',
      'Building Basic API Integrations',
    ],
  },
  {
    title: 'Python Automation',
    topicsLabel: 'Topics Covered',
    description:
      'Automate files, Excel, email, reports, and scheduled scripts for repetitive business workflows.',
    topics: [
      'Introduction to Automation',
      'Automating Repetitive Tasks',
      'Working with Files & Folders',
      'CSV Automation',
      'Excel Automation',
      'Email Automation',
      'Web Automation Fundamentals',
      'Data Extraction',
      'Report Automation',
      'Scheduled Scripts',
      'Practical Automation Workflows',
    ],
  },
  {
    title: 'Python for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Apply NumPy, Pandas, Matplotlib, and Seaborn to clean data, explore trends, calculate KPIs, and surface insights.',
    topics: [
      'NumPy',
      'Pandas',
      'Data Cleaning',
      'Data Transformation',
      'Exploratory Data Analysis',
      'Statistical Analysis Fundamentals',
      'Data Aggregation',
      'Data Visualization',
      'Matplotlib',
      'Seaborn',
      'Business KPIs',
      'Trend Analysis',
      'Correlation Analysis',
      'Business Insights',
    ],
  },
  {
    title: 'Python Interview & Problem-Solving Preparation',
    topicsLabel: 'Topics Covered',
    description:
      'Practice coding problems, data structures, OOP, SQL + Python scenarios, debugging, and mock interviews.',
    topics: [
      'Python Fundamentals Questions',
      'Coding Problems',
      'Data Structure Problems',
      'String Problems',
      'List & Dictionary Problems',
      'Function-Based Problems',
      'OOP Questions',
      'Exception Handling Questions',
      'SQL + Python Questions',
      'Real-World Python Scenarios',
      'Debugging Exercises',
      'Coding Challenges',
      'Mock Python Interviews',
    ],
  },
  {
    title: 'Industry Capstone Project',
    topicsLabel: 'Topics Covered',
    description:
      'Build an end-to-end Python solution: Raw Data → Python Processing → Database/API → Analysis → Insights → Final Solution.',
    topics: [
      'Understanding Business Requirements',
      'Data Collection',
      'Data Processing',
      'Data Cleaning',
      'Python Programming',
      'Database Integration',
      'API Integration',
      'Data Analysis',
      'Visualization',
      'Automation',
      'Business Insights',
      'Final Presentation',
    ],
  },
];

export default pythonBootcampCurriculum;
