/**
 * SQL Bootcamp — course structure (modules + topics).
 */

const sqlBootcampCurriculum = [
  {
    title: 'Database & SQL Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Build a foundation in relational databases, keys, constraints, SQL command types, and MySQL / PostgreSQL.',
    topics: [
      'Introduction to Databases',
      'What is SQL?',
      'Relational Databases',
      'DBMS & RDBMS',
      'Database Architecture',
      'Tables, Rows & Columns',
      'Primary Keys',
      'Foreign Keys',
      'Constraints',
      'Data Types',
      'NULL Values',
      'Database Relationships',
      'SQL Command Categories',
      'DDL, DML, DQL, DCL & TCL',
      'Introduction to MySQL / PostgreSQL',
    ],
  },
  {
    title: 'SQL Basics',
    topicsLabel: 'Topics Covered',
    description:
      'Create and change databases and tables, then write SELECT queries with filters, sorting, and logical operators.',
    topics: [
      'Creating Databases',
      'Creating Tables',
      'ALTER TABLE',
      'DROP & TRUNCATE',
      'INSERT',
      'UPDATE',
      'DELETE',
      'SELECT',
      'DISTINCT',
      'WHERE',
      'ORDER BY',
      'LIMIT',
      'Aliases',
      'Basic Filtering',
      'Comparison Operators',
      'Logical Operators',
    ],
  },
  {
    title: 'SQL Functions & Expressions',
    topicsLabel: 'Topics Covered',
    description:
      'Use aggregate, string, date, and conditional functions to transform and summarize data in queries.',
    groups: [
      {
        label: 'Aggregate Functions',
        items: ['COUNT', 'SUM', 'AVG', 'MIN', 'MAX'],
      },
      {
        label: 'String Functions',
        items: ['CONCAT', 'UPPER', 'LOWER', 'LENGTH', 'SUBSTRING', 'TRIM', 'REPLACE'],
      },
      {
        label: 'Date & Time Functions',
        items: [
          'CURRENT_DATE',
          'CURRENT_TIMESTAMP',
          'DATE Functions',
          'Date Difference',
          'Date Formatting',
          'Date-Based Analysis',
        ],
      },
      {
        label: 'Conditional Logic',
        items: ['CASE', 'COALESCE', 'NULLIF', 'IF / Conditional Expressions'],
      },
    ],
  },
  {
    title: 'GROUP BY & Data Aggregation',
    topicsLabel: 'Topics Covered',
    description:
      'Group and filter aggregated data to calculate revenue, customer, product, and KPI metrics.',
    topics: [
      'GROUP BY',
      'HAVING',
      'Aggregate Functions',
      'Multiple-Column Grouping',
      'Filtering Aggregated Data',
      'Conditional Aggregation',
      'Revenue Analysis',
      'Customer Analysis',
      'Product Analysis',
      'Business KPI Calculations',
    ],
  },
  {
    title: 'SQL Joins',
    topicsLabel: 'Topics Covered',
    description:
      'Combine related tables with INNER, LEFT, RIGHT, FULL, CROSS, and SELF joins — including multi-table problems.',
    topics: [
      'Understanding Relationships',
      'INNER JOIN',
      'LEFT JOIN',
      'RIGHT JOIN',
      'FULL OUTER JOIN',
      'CROSS JOIN',
      'SELF JOIN',
      'Multiple Table Joins',
      'Joining More Than Two Tables',
      'Join Conditions',
      'Handling Duplicate Records',
      'Practical Join Problems',
    ],
  },
  {
    title: 'Subqueries & Nested Queries',
    topicsLabel: 'Topics Covered',
    description:
      'Nest queries with scalar, correlated, EXISTS, IN, ANY, and ALL patterns for complex filters.',
    topics: [
      'Introduction to Subqueries',
      'Scalar Subqueries',
      'Single-Row Subqueries',
      'Multi-Row Subqueries',
      'Correlated Subqueries',
      'Subqueries with WHERE',
      'Subqueries with SELECT',
      'Subqueries with FROM',
      'EXISTS',
      'NOT EXISTS',
      'IN',
      'ANY & ALL',
      'Nested Query Problems',
    ],
  },
  {
    title: 'Common Table Expressions — CTEs',
    topicsLabel: 'Topics Covered',
    description:
      'Write readable SQL with WITH clauses, multiple CTEs, aggregations, joins, and recursive CTE fundamentals.',
    topics: [
      'Introduction to CTEs',
      'WITH Clause',
      'Single CTE',
      'Multiple CTEs',
      'CTE with Aggregations',
      'CTE with Joins',
      'Recursive CTE Fundamentals',
      'CTE vs Subqueries',
      'Writing Readable SQL',
      'Complex Business Queries Using CTEs',
    ],
  },
  {
    title: 'Window Functions',
    topicsLabel: 'Topics Covered',
    description:
      'Rank, lag, lead, and running calculations with OVER, PARTITION BY, and advanced analytical queries.',
    topics: [
      'Introduction to Window Functions',
      'OVER()',
      'PARTITION BY',
      'ORDER BY in Window Functions',
      'ROW_NUMBER',
      'RANK',
      'DENSE_RANK',
      'NTILE',
      'LAG',
      'LEAD',
      'FIRST_VALUE',
      'LAST_VALUE',
      'Running Totals',
      'Moving Averages',
      'Ranking Analysis',
      'Time-Series Analysis',
      'Advanced Analytical Queries',
    ],
  },
  {
    title: 'Data Manipulation & Advanced SQL',
    topicsLabel: 'Topics Covered',
    description:
      'Update and delete with joins, use views and temporary tables, and manage transactions with COMMIT and ROLLBACK.',
    topics: [
      'INSERT INTO SELECT',
      'UPDATE with Joins',
      'DELETE with Joins',
      'CASE-Based Updates',
      'Temporary Tables',
      'Views',
      'Transactions',
      'COMMIT',
      'ROLLBACK',
      'SAVEPOINT',
      'Error Handling Concepts',
    ],
  },
  {
    title: 'Database Design & Normalization',
    topicsLabel: 'Topics Covered',
    description:
      'Design relational models with ER concepts, keys, 1NF–3NF, denormalization, and star schema patterns.',
    topics: [
      'Database Design Fundamentals',
      'Entity-Relationship Concepts',
      'Entities & Attributes',
      'Relationships',
      'Primary & Foreign Keys',
      'Normalization',
      '1NF',
      '2NF',
      '3NF',
      'Denormalization',
      'Fact & Dimension Tables',
      'Star Schema',
      'Database Design Best Practices',
    ],
  },
  {
    title: 'SQL Performance & Optimization',
    topicsLabel: 'Topics Covered',
    description:
      'Improve query speed with indexes, EXPLAIN plans, join optimization, and filtering strategies.',
    topics: [
      'Understanding Query Performance',
      'Query Execution Concepts',
      'Indexes',
      'Clustered & Non-Clustered Index Concepts',
      'Composite Indexes',
      'Query Optimization',
      'EXPLAIN / Execution Plans',
      'Avoiding Unnecessary Queries',
      'Optimizing Joins',
      'Filtering Strategies',
      'Performance Best Practices',
    ],
  },
  {
    title: 'SQL for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Apply SQL to real-world analytics problems across sales, customers, marketing, HR, finance, and growth.',
    topics: [
      'Sales Analysis',
      'Customer Analysis',
      'Revenue Analysis',
      'Product Analysis',
      'Marketing Analytics',
      'HR Analytics',
      'Finance Analytics',
      'E-Commerce Analytics',
      'Customer Retention',
      'Cohort Analysis',
      'Conversion Analysis',
      'Growth Analysis',
      'KPI Calculations',
      'Time-Series Analysis',
    ],
  },
  {
    title: 'SQL Interview Preparation',
    topicsLabel: 'Topics Covered',
    description:
      'Practice query-based questions, coding challenges, business cases, and mock SQL interviews.',
    topics: [
      'SQL Fundamentals Questions',
      'Query-Based Questions',
      'Join Problems',
      'Subquery Problems',
      'CTE Questions',
      'Window Function Questions',
      'Data Analysis Questions',
      'Business Case Questions',
      'Query Optimization Questions',
      'Real-World SQL Scenarios',
      'SQL Coding Challenges',
      'Mock SQL Interviews',
    ],
  },
  {
    title: 'Industry Capstone Project',
    topicsLabel: 'Topics Covered',
    description:
      'Build an end-to-end SQL Data Analytics project: Raw Data → Database → SQL Analysis → Business Insights → Final Report.',
    topics: [
      'Understanding Business Requirements',
      'Database Design',
      'Data Import',
      'Data Cleaning',
      'Data Validation',
      'Writing SQL Queries',
      'Joins',
      'Aggregations',
      'Subqueries',
      'CTEs',
      'Window Functions',
      'KPI Development',
      'Business Analysis',
      'Query Optimization',
      'Business Insights',
      'Final Presentation',
    ],
  },
];

export default sqlBootcampCurriculum;
