/**
 * Tableau — course structure (modules + topics).
 */

const tableauCurriculum = [
  {
    title: 'Data Analytics Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Build an analytics foundation — the data lifecycle, KPIs, business questions, and turning data into decisions.',
    topics: [
      'Introduction to Data Analytics',
      'Business Intelligence Fundamentals',
      'Data Analytics Lifecycle',
      'Types of Data Analytics',
      'Structured & Unstructured Data',
      'Data Collection',
      'Data Cleaning',
      'Data Transformation',
      'Exploratory Data Analysis',
      'KPIs & Business Metrics',
      'Business Requirements',
      'Analytical Thinking',
      'Data-Driven Decision Making',
      'Turning Business Questions into Insights',
    ],
  },
  {
    title: 'Excel for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Prepare spreadsheet data for Tableau — functions, lookups, Pivot Tables, cleaning, and export-ready tables.',
    topics: [
      'Excel Fundamentals',
      'Data Formatting',
      'Tables',
      'Sorting & Filtering',
      'Excel Functions',
      'IF & Nested IF',
      'SUMIF & COUNTIF',
      'Lookup Functions',
      'XLOOKUP',
      'INDEX & MATCH',
      'Pivot Tables',
      'Pivot Charts',
      'Data Cleaning',
      'Data Preparation',
      'Preparing Excel Data for Tableau',
    ],
  },
  {
    title: 'SQL for Data Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Query relational data for Tableau — filters, joins, aggregations, window functions, and analytical SQL.',
    topics: [
      'SQL Fundamentals',
      'Database Fundamentals',
      'SELECT Statements',
      'Filtering Data',
      'Sorting Data',
      'Aggregate Functions',
      'GROUP BY',
      'HAVING',
      'Joins',
      'Subqueries',
      'CASE Statements',
      'Common Table Expressions',
      'Window Functions',
      'Data Cleaning with SQL',
      'Analytical Queries',
      'Connecting SQL Data with Tableau',
    ],
  },
  {
    title: 'Tableau Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Get productive in Tableau Desktop — workbooks, worksheets, dimensions, measures, filters, and your first viz.',
    topics: [
      'Introduction to Tableau',
      'Tableau Ecosystem',
      'Tableau Desktop',
      'Tableau Interface',
      'Tableau Workbooks',
      'Worksheets',
      'Dashboards',
      'Stories',
      'Dimensions & Measures',
      'Discrete & Continuous Fields',
      'Data Types',
      'Data Pane',
      'Marks Card',
      'Rows & Columns',
      'Filters',
      'Creating Your First Tableau Visualization',
    ],
  },
  {
    title: 'Connecting & Preparing Data',
    topicsLabel: 'Topics Covered',
    description:
      'Connect live and extract sources, model relationships, and keep data quality high before you visualize.',
    topics: [
      'Connecting to Data Sources',
      'Excel Data',
      'CSV Files',
      'SQL Databases',
      'Cloud Data Sources',
      'Web Data',
      'Live Connections',
      'Extract Connections',
      'Data Sources',
      'Data Relationships',
      'Joins',
      'Unions',
      'Blending',
      'Data Preparation',
      'Data Quality',
      'Managing Data Sources',
    ],
  },
  {
    title: 'Tableau Prep & Data Cleaning',
    topicsLabel: 'Topics Covered',
    description:
      'Profile, clean, and reshape data in Tableau Prep — flows, joins, pivots, and publishing prepared data.',
    topics: [
      'Introduction to Tableau Prep',
      'Tableau Prep Builder',
      'Connecting Data Sources',
      'Data Profiling',
      'Data Cleaning',
      'Removing Duplicates',
      'Handling Missing Values',
      'Changing Data Types',
      'Splitting Fields',
      'Grouping Values',
      'Renaming Fields',
      'Filtering Data',
      'Calculated Fields',
      'Joins',
      'Unions',
      'Pivoting Data',
      'Data Transformation',
      'Creating Reusable Data Flows',
      'Publishing Prepared Data',
    ],
  },
  {
    title: 'Tableau Visualizations',
    topicsLabel: 'Topics Covered',
    description:
      'Choose the right chart and build a full visual toolkit — from bars and maps to KPIs, dual-axis, and combinations.',
    topics: [
      'Data Visualization Fundamentals',
      'Choosing the Right Chart',
      'Bar Charts',
      'Column Charts',
      'Line Charts',
      'Area Charts',
      'Pie Charts',
      'Scatter Plots',
      'Maps',
      'Heat Maps',
      'Treemaps',
      'Bubble Charts',
      'Box Plots',
      'Histograms',
      'Gantt Charts',
      'Bullet Charts',
      'KPI Cards',
      'Tables',
      'Highlight Tables',
      'Dual-Axis Charts',
      'Combination Charts',
    ],
  },
  {
    title: 'Tableau Calculations & Advanced Analytics',
    topicsLabel: 'Topics Covered',
    description:
      'Go beyond basic charts — calculated fields, table calculations, parameters, sets, bins, and LOD expressions.',
    groups: [
      {
        label: 'Calculated Fields',
        items: [
          'Introduction to Calculated Fields',
          'Basic Calculations',
          'String Functions',
          'Date Functions',
          'Logical Functions',
          'Number Functions',
          'Aggregate Functions',
          'Conditional Calculations',
        ],
      },
      {
        label: 'Table Calculations',
        items: [
          'Running Total',
          'Difference',
          'Percentage of Total',
          'Moving Average',
          'Rank',
          'Window Calculations',
        ],
      },
      {
        label: 'Advanced Tableau',
        items: [
          'Parameters',
          'Sets',
          'Groups',
          'Bins',
          'Hierarchies',
          'Level of Detail Expressions',
          'FIXED LOD',
          'INCLUDE LOD',
          'EXCLUDE LOD',
          'Context Filters',
          'Advanced Filtering',
          'Dynamic Calculations',
        ],
      },
    ],
  },
  {
    title: 'Interactive Dashboards & Data Storytelling',
    topicsLabel: 'Topics Covered',
    description:
      'Design executive-ready dashboards — layout, actions, drill-down, device layouts, performance, and storytelling.',
    topics: [
      'Dashboard Fundamentals',
      'Dashboard Layout',
      'Dashboard Design Principles',
      'Containers',
      'Filters',
      'Interactive Filters',
      'Parameters',
      'Actions',
      'Filter Actions',
      'Highlight Actions',
      'URL Actions',
      'Dashboard Navigation',
      'Drill-Down',
      'Drill-Through',
      'Tooltips',
      'Dynamic Titles',
      'Interactive Charts',
      'Device Layouts',
      'Dashboard Performance',
      'Executive Dashboard Design',
      'Data Storytelling',
    ],
  },
  {
    title: 'Tableau Server / Tableau Cloud',
    topicsLabel: 'Topics Covered',
    description:
      'Publish and share securely — workbooks, data sources, permissions, refresh, subscriptions, and collaboration.',
    topics: [
      'Introduction to Tableau Cloud & Server',
      'Publishing Workbooks',
      'Publishing Data Sources',
      'Projects',
      'Workbooks',
      'Views',
      'User Management',
      'Permissions',
      'Sharing Dashboards',
      'Data Refresh',
      'Extract Refresh',
      'Scheduled Refresh',
      'Subscriptions',
      'Alerts',
      'Tableau Content Management',
      'Collaboration',
      'Security Fundamentals',
    ],
  },
  {
    title: 'Real-World Business Analytics Projects',
    topicsLabel: 'Topics Covered',
    description:
      'Practice the full analytics workflow: Business Requirement → Data Collection → Data Preparation → Analysis → Visualization → Dashboard → Insights → Business Presentation.',
    topics: [
      'Sales Analytics',
      'Finance Analytics',
      'Marketing Analytics',
      'HR Analytics',
      'Customer Analytics',
      'E-Commerce Analytics',
      'Operations Analytics',
    ],
  },
  {
    title: 'Industry Capstone Project',
    topicsLabel: 'Topics Covered',
    description:
      'Build an end-to-end Tableau Business Intelligence solution using Excel / SQL → Tableau Prep → Tableau Desktop → Calculations → Dashboard → Tableau Cloud/Server.',
    topics: [
      'Business Requirement Analysis',
      'Data Collection',
      'Data Cleaning',
      'Data Preparation',
      'Data Connections',
      'Data Modeling',
      'Calculated Fields',
      'LOD Expressions',
      'KPI Development',
      'Interactive Dashboard',
      'Data Storytelling',
      'Business Insights',
      'Dashboard Publishing',
      'Final Presentation',
    ],
  },
];

export default tableauCurriculum;
