/**
 * Careers page content. Edit `jobs` to add, close, or rewrite openings.
 * Interest forms post through the same marketing enquiry API as Contact Us.
 */

const careersData = {
  hero: {
    eyebrow: 'Careers',
    title: 'Build the bridge',
    titleAccent: 'between learning and work',
    subtitle:
      'iBridge360 is an EdTech and technology solutions company focused on online education, corporate training, and skill development. We are hiring mentors who can teach real skills, and interns who want hands-on business exposure.',
  },
  whyJoin: {
    eyebrow: 'Why iBridge360',
    title: 'Work that',
    titleAccent: 'learners can feel',
    subtitle:
      'Mentors, trainers, and business teams work on the same problem: closing the gap between what people study and what employers need.',
    items: [
      {
        title: 'Programs with an outcome',
        text: 'Data, full stack, analytics, and corporate upskilling built so a learner can show work, not only a certificate.',
      },
      {
        title: 'Products in daily use',
        text: 'LearnSmart LMS, online assessments, and Code Arena are the tools campuses, companies, and learners actually open.',
      },
      {
        title: 'Flexible locations',
        text: 'Training roles are open in Bengaluru and Hyderabad, with flexible arrangements based on training requirements.',
      },
      {
        title: 'Practitioners on the team',
        text: 'You will work with mentors and business teams who talk to learners, colleges, and clients every week.',
      },
    ],
  },
  hiring: {
    eyebrow: 'How hiring works',
    title: 'From interest',
    titleAccent: 'to a conversation',
    steps: [
      {
        step: '01',
        title: 'Share your interest',
        text: 'Open a role, review the details, and fill in the application form. No account needed.',
      },
      {
        step: '02',
        title: 'The team reads it',
        text: 'Your note lands in the same enquiry desk as Contact Us, tagged as a careers application.',
      },
      {
        step: '03',
        title: 'A conversation',
        text: 'If the role is a match, we write to the email you shared and set up a call.',
      },
      {
        step: '04',
        title: 'A clear reply',
        text: 'We follow up on the application. If we cannot move ahead, you still hear back.',
      },
    ],
  },
  roles: {
    eyebrow: 'Open roles',
    title: 'Roles open',
    titleAccent: 'right now',
    subtitle:
      'Mentor roles are full-time, part-time, or contract; the MBA internship runs 3–6 months. Filter by team or search by skill.',
  },
  openApplication: {
    eyebrow: 'Open application',
    title: 'Do not see',
    titleAccent: 'your role?',
    subtitle:
      'Send a general note. Tell us the kind of work you do and we will write back if a matching opening comes up.',
  },
  equalOpportunity:
    'iBridge360 reviews applications on skills and relevant experience. People from different academic paths, cities, and career stages are welcome to apply.',
  contact: {
    email: 'support@ibridge360.com',
    emailHref: 'mailto:support@ibridge360.com',
    phone: '+91 96112 60360',
    phoneHref: 'tel:+919611260360',
    address: '5th Block, Jayanagar, Bengaluru 560041',
  },
  jobs: [
    {
      id: "data-engineering-mentor",
      title: "Data Engineering Mentor",
      department: "Training & Education",
      location: "Bengaluru / Hyderabad / Flexible",
      workMode: "Flexible · client / college sessions",
      type: "Full-time / Part-time / Contract",
      experience: "2+ years",
      summary: "Train students and working professionals in practical Data Engineering, using real-world examples and projects.",
      about: "We are looking for an experienced Data Engineering Mentor who can train and guide students and working professionals in practical Data Engineering concepts. The ideal candidate has strong technical knowledge and can explain complex concepts in a simple, structured, and practical manner.",
      responsibilities: ["Conduct technical training sessions for students and working professionals.", "Explain Data Engineering concepts using real-world examples and projects.", "Design and deliver hands-on assignments, exercises, and projects.", "Mentor learners throughout their learning journey.", "Conduct assessments, doubt-clearing sessions, and technical discussions.", "Guide learners in building industry-relevant projects and portfolios.", "Keep course content updated with current industry practices.", "Provide feedback on learner performance and project work.", "Support learners with interview preparation and technical discussions.", "Conduct training sessions at client / college locations when required."],
      skills: ["SQL", "Python", "Data Warehousing", "ETL / ELT", "Data Pipelines", "AWS / Azure", "Pandas", "Linux / Shell Scripting", "Database Concepts", "Data Modelling", "Cloud Data Engineering", "Git / Version Control"],
      goodToHave: ["Apache Spark", "Airflow", "AWS services such as S3, Glue, Redshift", "Azure Data Factory", "Databricks", "Basic AI / ML concepts", "Experience working with real-world Data Engineering projects"],
      requirements: ["Strong communication and presentation skills.", "Ability to simplify technical concepts.", "Strong problem-solving skills.", "Hands-on industry/project experience.", "Passion for teaching and mentoring.", "Comfortable working with students, freshers, and working professionals.", "Comfortable travelling to different client / college locations when required."],
      skillOptions: ["SQL", "Python", "Data Warehousing", "ETL / ELT", "Data Pipelines", "AWS / Azure", "Pandas", "Linux / Shell Scripting", "Database Concepts", "Data Modelling", "Cloud Data Engineering", "Git / Version Control", "Apache Spark", "Airflow", "AWS services such as S3, Glue, Redshift", "Azure Data Factory", "Databricks"],
    },
    {
      id: "data-analytics-mentor",
      title: "Data Analytics Mentor",
      department: "Training & Education",
      location: "Bengaluru / Hyderabad / Flexible",
      workMode: "Flexible · client / college sessions",
      type: "Full-time / Part-time / Contract",
      experience: "2+ years",
      summary: "Train learners in Data Analytics and Business Intelligence through practical business use cases and dashboards.",
      about: "We are looking for a passionate Data Analytics Mentor to train students and working professionals in Data Analytics, Business Intelligence, and data-driven decision-making. The candidate should have strong practical knowledge of analytics tools and deliver engaging, project-based training.",
      responsibilities: ["Conduct Data Analytics training sessions.", "Explain concepts through practical business use cases.", "Deliver hands-on assignments and projects.", "Guide learners in building analytics dashboards and portfolios.", "Conduct assessments and doubt-clearing sessions.", "Review learner projects and provide constructive feedback.", "Help learners understand business problems and convert them into analytical solutions.", "Mentor learners on interview preparation and real-world scenarios.", "Keep training material updated according to industry requirements.", "Conduct training sessions at client / college locations when required."],
      skills: ["Advanced Excel", "SQL", "Power BI", "Data Visualization", "Data Cleaning", "Data Analysis", "Statistics", "Business Intelligence", "Dashboard Development", "Data Modelling", "Basic Python / Pandas"],
      goodToHave: ["Tableau", "Python", "Machine Learning fundamentals", "Power Query", "DAX", "Azure / AWS", "Experience with real-world business datasets"],
      requirements: ["Strong analytical and problem-solving skills.", "Excellent communication and presentation skills.", "Ability to explain concepts to beginners.", "Practical experience working with analytics tools.", "Strong understanding of business use cases.", "Passion for teaching and mentoring.", "Comfortable travelling to different client / college locations when required."],
      skillOptions: ["Advanced Excel", "SQL", "Power BI", "Data Visualization", "Data Cleaning", "Data Analysis", "Statistics", "Business Intelligence", "Dashboard Development", "Data Modelling", "Basic Python / Pandas", "Tableau", "Python", "Machine Learning fundamentals", "Power Query", "DAX"],
    },
    {
      id: "java-full-stack-mentor",
      title: "Java Full Stack Mentor",
      department: "Training & Education",
      location: "Bengaluru / Hyderabad / Flexible",
      workMode: "Flexible · client / college sessions",
      type: "Full-time / Part-time / Contract",
      experience: "2+ years",
      summary: "Deliver live-coding, project-based training in modern Java full-stack development.",
      about: "We are looking for an experienced Java Full Stack Mentor who can train and mentor learners in modern Java-based full-stack development. The candidate should have strong hands-on development experience and deliver practical, project-based training.",
      responsibilities: ["Conduct Java Full Stack development training.", "Deliver live coding and practical sessions.", "Explain programming concepts and development practices.", "Guide learners through industry-relevant projects.", "Create assignments and coding exercises.", "Review learner code and projects.", "Conduct technical assessments and doubt-clearing sessions.", "Mentor learners in debugging and problem-solving.", "Support learners with technical interview preparation.", "Conduct training sessions at client / college locations when required."],
      skills: ["Core Java", "Advanced Java", "OOP", "Spring Framework", "Spring Boot", "Hibernate / JPA", "REST APIs", "HTML", "CSS", "JavaScript", "React.js / Angular", "SQL", "MySQL / PostgreSQL", "Git / GitHub"],
      goodToHave: ["Microservices", "Docker", "Kubernetes", "AWS / Azure", "CI/CD", "Kafka", "Redis", "Cloud deployment", "System Design fundamentals"],
      requirements: ["Strong Java programming knowledge.", "Good development and debugging skills.", "Hands-on project experience.", "Strong communication skills.", "Ability to explain complex concepts simply.", "Passion for teaching and mentoring.", "Comfortable travelling to different client / college locations when required."],
      skillOptions: ["Core Java", "Advanced Java", "OOP", "Spring Framework", "Spring Boot", "Hibernate / JPA", "REST APIs", "HTML", "CSS", "JavaScript", "React.js / Angular", "SQL", "MySQL / PostgreSQL", "Git / GitHub", "Microservices", "Docker", "Kubernetes", "AWS / Azure", "CI/CD"],
    },
    {
      id: "cyber-security-mentor",
      title: "Cyber Security Mentor",
      department: "Training & Education",
      location: "Bengaluru / Hyderabad / Flexible",
      workMode: "Flexible · client / college sessions",
      type: "Full-time / Part-time / Contract",
      experience: "2+ years",
      summary: "Teach cybersecurity through hands-on labs, demonstrations, and real-world scenarios.",
      about: "We are looking for a knowledgeable Cyber Security Mentor to train and mentor students and aspiring cybersecurity professionals. The ideal candidate has practical cybersecurity experience and can explain security concepts through hands-on demonstrations, labs, and real-world scenarios.",
      responsibilities: ["Conduct Cyber Security training sessions.", "Explain cybersecurity concepts using practical examples.", "Conduct hands-on labs and security exercises.", "Guide learners through cybersecurity projects.", "Create assignments and practical assessments.", "Conduct vulnerability assessment and security-related demonstrations in authorized environments.", "Review learner projects and provide feedback.", "Conduct doubt-clearing and mentoring sessions.", "Prepare learners for cybersecurity interviews.", "Keep training content aligned with current industry practices.", "Conduct training sessions at client / college locations when required."],
      skills: ["Cyber Security Fundamentals", "Networking", "Linux", "Windows Security", "Ethical Hacking Fundamentals", "Web Application Security", "Vulnerability Assessment", "Penetration Testing Concepts", "OWASP", "Network Security", "Security Tools", "Cryptography Fundamentals", "Security Monitoring"],
      goodToHave: ["SIEM", "SOC Operations", "Cloud Security", "Python / Bash", "Digital Forensics", "Incident Response", "CEH / Security+ / OSCP or relevant certifications", "Experience with cybersecurity labs"],
      requirements: ["Strong cybersecurity fundamentals.", "Practical security experience.", "Good communication and presentation skills.", "Ability to conduct hands-on training.", "Strong problem-solving skills.", "Passion for teaching and mentoring.", "Comfortable travelling to different client / college locations when required."],
      skillOptions: ["Cyber Security Fundamentals", "Networking", "Linux", "Windows Security", "Ethical Hacking Fundamentals", "Web Application Security", "Vulnerability Assessment", "Penetration Testing Concepts", "OWASP", "Network Security", "Security Tools", "Cryptography Fundamentals", "Security Monitoring", "SIEM", "SOC Operations", "Cloud Security", "Python / Bash", "Digital Forensics"],
    },
    {
      id: "accounts-finance-mentor",
      title: "Accounts & Finance Mentor",
      department: "Training & Education",
      location: "Bengaluru / Hyderabad / Flexible",
      workMode: "Flexible · client / college sessions",
      type: "Full-time / Part-time / Contract",
      experience: "2+ years",
      summary: "Train students and professionals in practical accounting, GST, Tally, and Zoho Books using real business transactions.",
      about: "We are looking for an experienced Accounts & Finance Mentor who can train students and professionals in practical accounting concepts and accounting software. The ideal candidate has strong knowledge of accounting fundamentals, GST, Tally, and Zoho Books, and can explain concepts using real-world business transactions.",
      responsibilities: ["Conduct accounting and finance training sessions.", "Teach accounting concepts using practical examples.", "Train learners on Tally and Zoho Books.", "Explain real-world accounting transactions and workflows.", "Conduct practical assignments and assessments.", "Guide learners through bookkeeping and financial reporting.", "Explain GST concepts and practical accounting treatment.", "Conduct doubt-clearing sessions.", "Review learner assignments and provide feedback.", "Prepare learners for accounting-related interviews.", "Conduct training sessions at client / college locations when required."],
      skills: ["Accounting Fundamentals", "Journal Entries", "Ledger & Trial Balance", "Profit & Loss Account", "Balance Sheet", "Bank Reconciliation", "Accounts Payable & Receivable", "GST", "TDS", "Tally Prime", "Zoho Books", "Excel", "Bookkeeping"],
      goodToHave: ["Payroll", "Income Tax fundamentals", "GST Returns", "E-Invoicing", "E-Way Bill", "Financial Reporting", "MIS Reporting", "Advanced Excel", "Practical experience handling business accounts"],
      requirements: ["Strong accounting fundamentals.", "Practical knowledge of Tally and Zoho Books.", "Good understanding of GST.", "Strong communication and presentation skills.", "Ability to explain accounting concepts to beginners.", "Practical industry experience preferred.", "Passion for teaching and mentoring.", "Comfortable travelling to different client / college locations when required."],
      skillOptions: ["Accounting Fundamentals", "Journal Entries", "Ledger & Trial Balance", "Profit & Loss Account", "Balance Sheet", "Bank Reconciliation", "Accounts Payable & Receivable", "GST", "TDS", "Tally Prime", "Zoho Books", "Excel", "Bookkeeping", "Payroll", "Income Tax fundamentals", "GST Returns", "E-Invoicing", "E-Way Bill"],
    },
    {
      id: "mba-intern",
      title: "MBA Intern",
      department: "Business Operations",
      location: "Bengaluru",
      workMode: "On-site",
      type: "Internship · 3–6 months",
      experience: "Freshers / MBA students / recent graduates",
      summary: "Get hands-on exposure to business activities across lead management, marketing, research, and operations at an EdTech company.",
      about: "We are looking for motivated MBA Interns who want practical exposure to business activities in a growing EdTech and technology environment. The intern will work with different teams and support various business requirements.",
      responsibilities: ["Assist with day-to-day business activities and assigned projects.", "Support lead management, customer communication, and follow-ups.", "Assist with marketing activities, market research, and business development.", "Coordinate with internal teams and support business operations.", "Prepare reports, presentations, and maintain business records.", "Support management with various business-related tasks and initiatives."],
      skills: ["Good verbal and written communication", "Strong interpersonal and coordination skills", "Basic understanding of business concepts", "Good knowledge of MS Excel / Google Sheets", "Analytical and problem-solving skills", "Good organizational and time-management skills", "Willingness to learn and take ownership"],
      goodToHave: ["Basic knowledge of Digital Marketing", "CRM knowledge", "Market research experience", "Sales or customer interaction experience", "Excel / Power BI knowledge", "Business analytics knowledge"],
      requirements: ["MBA students from relevant specializations.", "Recent MBA graduates.", "Freshers looking for practical corporate exposure.", "Candidates with strong communication and interpersonal skills.", "Proactive, adaptable, organized, and eager to learn, with the ability to take responsibility across business activities."],
      gains: ["Hands-on corporate experience.", "Exposure to multiple business functions.", "Experience working on live business projects.", "Practical experience in business communication, coordination, and reporting.", "Opportunity to work with experienced professionals."],
      skillOptions: ["MS Excel / Google Sheets", "Communication", "Lead management / CRM", "Digital Marketing", "Market research", "Business analytics", "Power BI", "Sales / customer interaction"],
    },
  ],
};

export default careersData;
