/**
 * Data Engineering — course structure (modules + topics).
 */

const dataEngineeringCurriculum = [
  {
    title: 'Business & Data Fundamentals',
    topicsLabel: 'Topics Covered',
    description:
      'Build a strong understanding of business processes, industry workflows, data concepts, and the fundamentals of relational database management systems.',
    topics: [
      'Business & Data Fundamentals',
      'Data Types & Data Sources',
      'Database Fundamentals',
      'RDBMS Concepts',
      'Entities & Relationships',
      'Tables, Rows & Columns',
      'Primary & Foreign Keys',
      'Constraints & Data Integrity',
      'Transactions & ACID Properties',
      'OLTP vs OLAP',
      'Data Lifecycle & Data Flow',
      'Introduction to Data Engineering',
    ],
  },
  {
    title: 'SQL for Data Engineering',
    topicsLabel: 'Topics Covered',
    description:
      'Learn to query, manipulate, and optimize relational databases using SQL — one of the most essential skills for Data Engineers.',
    topics: [
      'SQL Syntax & Query Structure',
      'SELECT, WHERE & ORDER BY',
      'GROUP BY & HAVING',
      'Aggregate Functions',
      'SQL Functions',
      'Joins & Relationships',
      'Subqueries & CTEs',
      'CASE Statements',
      'Data Manipulation — INSERT, UPDATE & DELETE',
      'Window Functions',
      'Views & Temporary Tables',
      'Query Optimization',
      'Indexing & Performance Tuning',
    ],
  },
  {
    title: 'Data Warehousing & ETL',
    topicsLabel: 'Topics Covered',
    description:
      'Understand how enterprise data warehouses are designed and how ETL processes move and transform data for analytics.',
    topics: [
      'Data Warehouse Fundamentals',
      'OLTP vs Data Warehouse',
      'Data Warehouse Architecture',
      'ETL & ELT Concepts',
      'Data Extraction & Loading',
      'Data Transformation',
      'Data Modeling',
      'Fact & Dimension Tables',
      'Star Schema',
      'Snowflake Schema',
      'Slowly Changing Dimensions',
      'Data Quality & Validation',
      'Batch Data Processing',
      'Incremental Data Loading',
      'Data Warehouse Reporting',
    ],
  },
  {
    title: 'Python Programming',
    topicsLabel: 'Topics Covered',
    description:
      'Develop strong programming skills to build, automate, and manage data engineering workflows.',
    topics: [
      'Python Fundamentals',
      'Variables & Data Types',
      'Operators & Expressions',
      'Conditional Statements',
      'Loops & Iterations',
      'Functions & Lambda Functions',
      'Lists, Tuples, Sets & Dictionaries',
      'String Operations',
      'Modules & Packages',
      'File Handling',
      'Exception Handling',
      'Object-Oriented Programming',
      'Regular Expressions',
      'JSON & XML Processing',
      'Database Connectivity',
      'Virtual Environments & Package Management',
    ],
  },
  {
    title: 'Data Processing & Analysis with Pandas',
    topicsLabel: 'Topics Covered',
    description:
      "Learn to clean, transform, analyze, and visualize data using Python's powerful data analysis libraries.",
    topics: [
      'NumPy Fundamentals',
      'Pandas Series & DataFrames',
      'Data Import & Export',
      'CSV, Excel & JSON Data',
      'Data Inspection & Exploration',
      'Data Cleaning',
      'Handling Missing Values',
      'Duplicate Data Management',
      'Data Type Conversion',
      'Filtering & Sorting',
      'Merge, Join & Concatenation',
      'GroupBy & Aggregation',
      'Pivot Tables',
      'Date & Time Operations',
      'Data Transformation',
      'Basic Data Visualization',
    ],
  },
  {
    title: 'Power BI for Business Intelligence',
    topicsLabel: 'Topics Covered',
    description:
      'Create interactive dashboards and generate business insights through data visualization.',
    topics: [
      'Power BI Overview',
      'Power BI Desktop',
      'Data Import & Connections',
      'Power Query',
      'Data Cleaning & Transformation',
      'Data Modeling',
      'Relationships & Cardinality',
      'Calculated Columns',
      'Measures & KPIs',
      'DAX Fundamentals',
      'DAX Functions',
      'Charts & Visualizations',
      'Filters & Slicers',
      'Drill-Down & Drill-Through',
      'Time Intelligence',
      'Dashboard Development',
      'Power BI Service',
      'Row-Level Security',
    ],
  },
  {
    title: 'AWS Cloud Services',
    topicsLabel: 'Topics Covered',
    description:
      'Learn the core AWS services used to deploy and manage cloud-based data engineering solutions.',
    topics: [
      'Cloud Computing Fundamentals',
      'AWS Account & IAM',
      'AWS Management Console',
      'Amazon EC2',
      'Amazon S3',
      'Amazon RDS',
      'AWS VPC Fundamentals',
      'Cloud Storage',
      'Data Storage & Access',
      'Security & Permissions',
      'Compute & Database Services',
      'AWS CLI Basics',
      'Data Upload & Management',
      'Cloud-Based Data Workflows',
      'Deploying Data Solutions on AWS',
    ],
  },
  {
    title: 'Linux & Shell Scripting',
    topicsLabel: 'Topics Covered',
    description:
      'Build command-line skills and automate repetitive tasks using Linux and Shell scripting.',
    topics: [
      'Linux Fundamentals',
      'Linux File System',
      'Essential Linux Commands',
      'File & Directory Management',
      'File Permissions & Ownership',
      'Users & Groups',
      'Process Management',
      'Package Management',
      'Vi/Vim Editor',
      'Pipes & Redirection',
      'Grep & Find',
      'AWK & Sed',
      'Environment Variables',
      'Shell Scripting',
      'Conditional Statements & Loops',
      'Functions in Shell',
      'Cron Job Scheduling',
      'Automation with Shell Scripts',
    ],
  },
  {
    title: 'Industry Capstone Project',
    headline: 'Build an End-to-End Data Engineering Solution',
    topicsLabel: 'Project Components',
    description:
      'This capstone is one of the strongest proofs of your skills. You will design and deliver a complete Data Engineering solution — from business problem definition to cloud integration, dashboards, documentation, and a final presentation.',
    topics: [
      'Business Problem Definition',
      'Data Source Identification',
      'Data Extraction',
      'Database Design',
      'Data Ingestion',
      'ETL Pipeline Development',
      'Data Cleaning & Transformation',
      'Data Warehouse Design',
      'Data Processing with Python',
      'SQL-Based Data Analysis',
      'AWS Cloud Integration',
      'Data Validation & Quality Checks',
      'Power BI Dashboard Development',
      'Business KPI & Reporting',
      'End-to-End Pipeline Testing',
      'Project Documentation',
      'Git/GitHub Project Management',
      'Final Project Presentation',
    ],
  },
];

export default dataEngineeringCurriculum;
